### ISSUE TITLE
argument 3 has unexpected type 'PingRequest'

### ISSUE THREAD

**Issue by random29** [evilsocket/opensnitch#450] opened 2021-07-06 18:54 UTC
Hi there, dear developer UwU

**Describe the bug**
UI is not refreshing. No captured packages, no refreshing of rules.

**To Reproduce**
Just start opensnitch-ui

**Post error logs:** 
Ping exception:  UIService._update_stats_trigger[str, str, PingRequest].emit(): argument 3 has unexpected type 'PingRequest'
Ping exception:  UIService._update_stats_trigger[str, str, PingRequest].emit(): argument 3 has unexpected type 'PingRequest'
Ping exception:  UIService._update_stats_trigger[str, str, PingRequest].emit(): argument 3 has unexpected type 'PingRequest'
When I start opensnitch-ui

**OS (please complete the following information):**
 - OS: Manjaro 
 - Window Manager: xfce4
 - Kernel version: 5.12.9-1-MANJARO
Installed from aur ofc

**Comment by emansom** [comment] 2021-07-07 08:37
Observing same behavior on Arch, package `opensnitch-git` from AUR.

**Comment by gustavo-iniguez-goya** [comment] 2021-07-07 10:28
Hi,

Please, see: https://github.com/evilsocket/opensnitch/pull/442#issuecomment-868806925

**Comment by random29** [comment] 2021-07-07 19:39
> Hi,
> 
> Please, see: [#442 (comment)](https://github.com/evilsocket/opensnitch/pull/442#issuecomment-868806925)

Sorry, but person in aur updated to last commit and I still get this thing

**Comment by gustavo-iniguez-goya** [comment] 2021-07-07 19:49
ping @shollingsworth

**Comment by shollingsworth** [comment] 2021-07-07 20:28
I'll spin up a VM or container and see if I can reproduce.

**Comment by shollingsworth** [comment] 2021-07-08 05:46
This patch seems to have fixed the build. 
Tested on arch:latest 

it does seem to add one more package as a build dep `qt5-tools`

```
diff --git a/PKGBUILD b/PKGBUILD
index fb8f390..92abb5a 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -3,13 +3,13 @@
 # Contributor: lsf
 # Contributor: Adam Hose <adis@blad.is>
 pkgname=opensnitch-git
-pkgver=1.4.0.rc.1.r2.148526e
+pkgver=1.4.0.rc.2.r27.8580281
 pkgrel=1
 pkgdesc="A GNU/Linux port of the Little Snitch application firewall"
 arch=('i686' 'x86_64' 'armv6h' 'armv7h' 'aarch64')
 url="https://github.com/evilsocket/opensnitch"
 license=('GPL3')
-makedepends=('git' 'go' 'python-setuptools' 'python-grpcio-tools')
+makedepends=('git' 'go' 'python-setuptools' 'python-grpcio-tools' 'qt5-tools')
 depends=('libnetfilter_queue' 'libpcap' 'python-grpcio' 'python-protobuf'
          'python-pyinotify' 'python-slugify' 'python-pyqt5')
 optdepends=('logrotate: for logfile rotation support')
@@ -36,7 +36,6 @@ prepare() {
 build() {
   cd "$srcdir/${pkgname%-git}"
 
-  pushd proto
   export GOPATH="$srcdir/gopath"
   export CGO_CPPFLAGS="${CPPFLAGS}"
   export CGO_CFLAGS="${CFLAGS}"
@@ -45,7 +44,8 @@ build() {
   export GOFLAGS="-buildmode=pie -trimpath -ldflags=-linkmode=external -mod=mod"
   export PATH=${PATH}:${GOPATH}/bin
   go get github.com/golang/protobuf/protoc-gen-go
-  # make ../daemon/ui/protocol/ui.pb.go
+
+  pushd proto
   make
   popd
 
@@ -53,20 +53,21 @@ build() {
   make
   popd
 
-  # Clean mod cache for makepkg -C
-  go clean -modcache
-
   pushd ui
+
   pyrcc5 -o opensnitch/resources_rc.py opensnitch/res/resources.qrc
-  python setup.py build
+  sed -i 's/^import ui_pb2/from . import ui_pb2/' opensnitch/ui_pb2*
+
   popd
+
+  go clean -modcache
 }
 
 package() {
   cd "$srcdir/${pkgname%-git}"
   pushd ui
   export PYTHONHASHSEED=0
-  python setup.py install --root="$pkgdir/" --optimize=1 --skip-build
+  python setup.py install --root="$pkgdir/"
   popd
 
   install -d "$pkgdir/etc/${pkgname%-git}d/rules"
```

**Comment by gustavo-iniguez-goya** [comment] 2021-07-08 10:45
Thank you @shollingsworth !

If it's fixed, please @random29 close it. Or if you can confirm @emansom that it's fixed, let me know and I'll close it as fixed.

**Comment by emansom** [comment] 2021-07-08 13:00
With patched PKGBUILD from @shollingsworth above, it works as expected.

@shollingsworth What's the reasoning for removing --optimize from the setup.py install command?

**Comment by shollingsworth** [comment] 2021-07-08 13:49
> With patched PKGBUILD from @shollingsworth above, the UI shows up as expected again. However there's an error when trying to save/apply the node configuration.
> ![afbeelding](https://user-images.githubusercontent.com/981494/124926526-ea90a500-dffd-11eb-9519-c41938b08612.png)

I'm not able to duplicate that behavior on a fresh install. I can't even find a reference to that file in the source :\
Settings seem to apply fine in my testing.

also you can put in `--optimize=1` but the `--skip-build` flag does break the install.

**Comment by gustavo-iniguez-goya** [comment] 2021-07-08 14:06
The file `/etc/opensnitchd/opensnitch.o` is the [eBPF compiled module](https://github.com/evilsocket/opensnitch/tree/master/ebpf_prog). I compile it when I build the DEB and RPM packages, so if you want to use the "ebpf" proc monitor method you or the AUR package's maintainer should compile and distribute it.

You can always get it from the DEB package (`$ wget https://github.com/evilsocket/opensnitch/releases/download/v1.4.0-rc.2/opensnitch_1.4.0.rc2-1_amd64.deb ; dpkg -x opensnitch_1.4.0.rc2-1_amd64.deb xxx ; sudo cp xxx/etc/opensnitchd/opensnitch.o /etc/opensnitchd/opensnitch.o`)

To get rid of that message change the "Process monitor method" to "proc" (ui -> preferences -> nodes)

**Comment by gustavo-iniguez-goya** [comment] 2021-07-08 18:07
https://aur.archlinux.org/packages/opensnitch-ebpf-module-git/

someone created this AUR today :)

**Comment by shollingsworth** [comment] 2021-07-08 18:14
Still working out the kinks with the AUR package maintainer.

**Comment by lsfxz** [comment] 2021-07-08 18:37
> https://aur.archlinux.org/packages/opensnitch-ebpf-module-git/
> 
> someone created this AUR today :)

That was me as well ;)

I just wanted to chime in to say: Feel free to @ me directly on here if (packaging related) issues with the AUR packages crop up; might be a bit more "comfortable" than always having to head over to the AUR and leave a comment there :)

**Comment by shollingsworth** [comment] 2021-07-08 18:39
Looks like that last patch worked. Thanks @lsfxz :) 

@gustavo-iniguez-goya I think we can close this issue.

**Comment by gustavo-iniguez-goya** [comment] 2021-07-08 18:56
:+1:  thank you very much @shollingsworth @lsfxz

**Closed by gustavo-iniguez-goya** 2021-07-08 18:56 UTC

**Comment by shollingsworth** [comment] 2021-07-08 18:57
BTW, if anybody is interested, I made a repo for the arch testing I did.
https://github.com/shollingsworth/opensnitch-docker-testing
