### ISSUE TITLE
[BUG] GUI crash on start due to module 'PyQt5.Qt' has no attribute 'QItemDelegate'

### ISSUE THREAD

**Issue by darkfishy** [evilsocket/opensnitch#821] opened 2023-01-29 10:50 UTC
- [x] Please, check the FAQ and Known Problems pages before creating the bug report:
    https://github.com/evilsocket/opensnitch/wiki/FAQs
    https://github.com/evilsocket/opensnitch/wiki/Known-problems

**Describe the bug**
`opensnitch-ui` version `1.5.3` crashes on start with latest `pyqt5` version `5.15.8`

Include the following information:
 - OpenSnitch version: **1.5.3**
 - OS: **ArchLinux x86_64**
 - Version: **Rolling; systemd 252.4-2-arch**
 - Window Manager: **SwayWM 1.8**
 - Kernel version: **6.1.8-native_amd**

**To Reproduce**
Upgrade/Install system Python `PyQt5` package from version `5.15.7` to version `5.15.8`.

Steps to reproduce the behaviour:
1. Open `opensnitch-ui` from a terminal
2. Application crashes with Python AttributeError for module PyQt5.Qt
3. See error below

**Post error logs:** 
Crash of the GUI: 

```python
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 23, in <module>
    from opensnitch.service import UIService
  File "/usr/lib/python3.10/site-packages/opensnitch/service.py", line 17, in <module>
    from opensnitch.dialogs.stats import StatsDialog
  File "/usr/lib/python3.10/site-packages/opensnitch/dialogs/stats.py", line 18, in <module>
    from opensnitch.customwidgets.main import ColorizedDelegate, ConnectionsTableModel
  File "/usr/lib/python3.10/site-packages/opensnitch/customwidgets/main.py", line 11, in <module>
    class ColorizedDelegate(Qt.QItemDelegate):
AttributeError: module 'PyQt5.Qt' has no attribute 'QItemDelegate'
```

**Expected behavior (optional)**
GUI starts with no error

**Additional context**
`PyQt5` seems to have changed their module structure and now certain widgets aren't available from the `Qt` module. Instead they are now under `QtWidgets` module. However, I couldn't find a reference to this change under [release notes](https://www.riverbankcomputing.com/news/PyQt_v5.15.8_Released).

**Patch**
```diff
diff --unified --recursive --text opensnitch.orig/customwidgets/main.py opensnitch.new/customwidgets/main.py
--- opensnitch.orig/customwidgets/main.py   2023-01-29 16:48:01.639124253 +1100
+++ opensnitch.new/customwidgets/main.py    2023-01-29 16:47:35.660013547 +1100
@@ -1,16 +1,16 @@
 from PyQt5 import Qt, QtCore
 from PyQt5.QtGui import QColor, QStandardItemModel, QStandardItem
 from PyQt5.QtSql import QSqlQueryModel, QSqlQuery, QSql
-from PyQt5.QtWidgets import QTableView
+from PyQt5.QtWidgets import QTableView, QItemDelegate, QStyle
 from PyQt5.QtCore import QItemSelectionModel, pyqtSignal, QEvent
 import time
 import math

 from PyQt5.QtCore import QCoreApplication as QC

-class ColorizedDelegate(Qt.QItemDelegate):
+class ColorizedDelegate(QItemDelegate):
     def __init__(self, parent=None, *args, config=None):
-        Qt.QItemDelegate.__init__(self, parent, *args)
+        QItemDelegate.__init__(self, parent, *args)
         self._config = config
         self._alignment = QtCore.Qt.AlignLeft | QtCore.Qt.AlignHCenter

@@ -29,7 +29,7 @@
                 if 'alignment' in self._config:
                     self._alignment = self._config['alignment']

-                if option.state & Qt.QStyle.State_Selected:
+                if option.state & QStyle.State_Selected:
                     painter.setBrush(painter.brush())
                     painter.setPen(painter.pen())
                 painter.drawText(option.rect, self._alignment, value)
```

**Comment by uffejakobsen** [comment] 2023-01-29 15:03
Just to chime in here - I see exact the same problem with
opensnitch-git 1.6.0rc2.r22.acac681-1
opensnitch-ebpf-module-git 1.6.0rc3.r31.276966a-1

Also on archlinux

**Comment by gustavo-iniguez-goya** [comment] 2023-01-29 19:20
Thank you @darkfishy @uffejakobsen !!

I think this is fixed now, could you confirm that it's working now?

**Comment by bingobr** [comment] 2023-01-29 19:35
> Thank you @darkfishy @uffejakobsen !!
> 
> I think this is fixed now, could you confirm that it's working now?

the latest commit solved the issue for me. I was wondering why a fresh install was not working. all good now.

**Comment by gustavo-iniguez-goya** [comment] 2023-01-29 22:34
update: There's a message on the PyQt mailing list, stating that SIP seems to be broken:
_" When PyQt5 is built with sip 6.7.6, the PyQt5.Qt class is empty:
(...)
Works fine after reverting to sip 6.7.5"_

https://www.riverbankcomputing.com/pipermail/pyqt/2023-January/045137.html

**Comment by darkfishy** [comment] 2023-01-30 02:09
> update: There's a message on the PyQt mailing list, stating that SIP seems to be broken:

Thanks @gustavo-iniguez-goya Just saw this message on [commit history](https://github.com/archlinux/svntogit-packages/commit/76c26d5df3572d957f7fa966125d93545503f4ba) of `PyQt5` package on Archlinux from the maintainer (_author of mailing list post_). Rebuilt `PyQt5` does fix the issue without requiring any changes to `opensnitch-ui`.

I have also verified your changes with version `1.5.3` and it works.

Said so, I think it might still be prudent to keep your changes.

**Comment by gustavo-iniguez-goya** [comment] 2023-01-30 10:34
thank you! I'll keep an eye on the mailinglist thread to see if this problem was intended or not.

**Closed by gustavo-iniguez-goya** 2023-01-30 10:34 UTC

**Comment by uffejakobsen** [comment] 2023-01-30 10:41
I can confirm that my existing opensnitch installations on archlinux works again after updating to 
python-pyqt5-5.15.8_2 (defect package was python-pyqt5-5.15.8_1)

Thanks :-) :+1:
