### ISSUE TITLE
[Feature Request] Support for Debian

### ISSUE THREAD

**Issue by Danny3** [evilsocket/opensnitch#798] opened 2023-01-13 17:07 UTC
### Summary:

I have installed OpenSnitch on Debian 12 with the unstable repository and it's working great.

But I would like to be able to install this program on Debian from Debian's repository itself with apt, like other programs.
Downloading and installing it the current way with downloading files and installing them is ok, but it would be easier and faster for many people if this program would be available in Debian's repository.
It would also be good for updates which can be taken care by the package manager.

Ans some people have saved commands or scripts with which programs to be automatically installed from the repository after a fresh install of the OS, so this should be easier for them too.

But it seems that there's a very long queue and a more involved process until a new package is accepted into the repository, so in my opinion the sooner this process is started, the better.

I think nothing can be done to speed this up, so starting the process sooner should be better than later.

Please have a look how at this comment:
https://github.com/JonMagon/KDiskMark/issues/110#issuecomment-1380872420

Thank you!

**Comment by Tachi107** [comment] 2023-01-13 17:11
Duplicate of #304

**Comment by gustavo-iniguez-goya** [comment] 2023-01-13 17:42
Well, there's an ITP request already opened, and (recently) there has been an offer by a Deb dev to sponsor/mentor the packaging for Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909567

On the other hand, I don't know how often is that the upstream is also the maintainer of the Debian package, but (as of today,) I'd like to focus on developing the app.

I'll close this issue, since #304 is already opened.

**Closed by gustavo-iniguez-goya** 2023-01-13 17:42 UTC
Labels: feature

**Comment by Danny3** [comment] 2023-01-13 18:40
Oh, sorry, I missed that.

I understand, thank you!

**Comment by petterreinholdtsen** [comment] 2023-04-27 18:12
Sadly the last upload, https://tracker.debian.org/pkg/opensnitch, have not made it into testing and will not be included in the next release unless the maintainer step up to fix the issue.  I've failed to reach the maintainer via email and IRC, and am unsure if the issue is known.

**Comment by gustavo-iniguez-goya** [comment] 2023-04-27 22:45
Sorry @petterreinholdtsen , I'll connect to the irc asap.
