### ISSUE TITLE
non disapering qt prompt

### ISSUE THREAD

**Issue by in1t3r** [evilsocket/opensnitch#67] opened 2017-05-12 17:06 UTC
Important bug labeling connection as forever and clicking allow continue prompting you for the same ip all the time. Ways to reproduce:
first of all remove all references for firefox in opensnitch.db with sqlitebrowser.
start not whitlelisted app for example firefox without proxy
then start a ssh connection somewhere which is not blocked which is improvement login via ssh.
return back to the firefox prompt and check billion dns prompts that appear no matter if you click forever and allow.
![2017-05-12-190501_442x213_scrot](https://cloud.githubusercontent.com/assets/993923/26008668/06cea31c-3746-11e7-85cf-21e3809de2f2.png)
click it thousand times it still ain't gonna disappear.

**Comment by in1t3r** [comment] 2017-05-12 17:19
update once you delete all references for firefox actually prompts appear at least few times when you select forever. For example if you are running privoxy and select forever allow connection of firefox to 8118 it will still ask you 3 times. Also if you have many tabs it will ask you multiple time for the same ip on nonproxified version of firefox.

**Comment by in1t3r** [comment] 2017-05-12 17:28
![2017-05-12-192551_1916x1041_scrot](https://cloud.githubusercontent.com/assets/993923/26009402/ebe235a2-3748-11e7-83ec-d8d8ab62d028.png)
Does this rules look sane too anyone of you that is what happen when I don't open ssh connection that is not blocked in background just when I start regularly firefox?
check again where its messed up @adisbladis

**Comment by adisbladis** [comment] 2017-05-14 06:35
I had a look of this and the problem is that all connections that are queued are going to show up in the dialog.
A normal website load from your browser opens up a whole bunch of connections

We would need to re-check if there has been any rule changes from when the connection was queued before popping up in the UI, that would presumably resolve this.

A related issue (that we are seeing duplicated rules) is that we should add unique constraints to the db.
I have created a new issue for this (https://github.com/evilsocket/opensnitch/issues/70).

**Comment by adisbladis** [comment] 2017-05-14 08:04
Also it seems like sometimes we are getting multiple callbacks for the same outbound connection.
I don't really know why yet..

**Comment by adisbladis** [comment] 2017-05-16 13:36
@in1t3r Could you check the behaviour since https://github.com/evilsocket/opensnitch/pull/72
I'm quite interested to know if you are still experiencing issues after that

**Comment by adisbladis** [comment] 2017-05-23 03:16
@in1t3r Unless I can get some more info on this soon-ish I'm going to close it since I can't reproduce the described behaviour.

**Comment by in1t3r** [comment] 2017-05-23 13:08
It is not reproducible anymore after few updates. That was only 
appearing in the version before queue of messages was not fixed so yeah 
close the issue.

**Closed** 2017-05-23 13:09 UTC
