### ISSUE TITLE
UI issue communicating with service on startup

### ISSUE THREAD

**Issue by dissona** [evilsocket/opensnitch#849] opened 2023-02-13 23:58 UTC
Manjaro KDE 5.26.5
Kernel 5.15.93-1-MANJARO
opensnitch 1.5.5

I updated a few packages on manjaro and the UI is now broken on startup

im running opensnitch-ui on startup
Status on opensnitch-ui is bugged, just says nothing and start/stop button does nothing
running `systemctl status opensnitchd.service` says the service is running fine

I have tried reinstalling and deleting cache and /etc/opensnitchd

The only way to fix it is restart opensnitchd.service, then everything works fine

Here are the logs:

`[2m[2023-02-13 10:54:56][0m [97m[43m WAR [0m Error while pinging UI service: rpc error: code = DeadlineExceeded desc = Deadline Exceeded, state: READY
[2m[2023-02-13 10:54:58][0m [97m[43m WAR [0m Error while pinging UI service: rpc error: code = DeadlineExceeded desc = context deadline exceeded, state: READY
[2m[2023-02-13 10:55:00][0m [97m[43m WAR [0m Error while pinging UI service: rpc error: code = DeadlineExceeded desc = context deadline exceeded, state: READY
[2m[2023-02-13 10:55:02][0m [97m[43m WAR [0m Error while pinging UI service: rpc error: code = DeadlineExceeded desc = context deadline exceeded, state: READY
[2m[2023-02-13 10:55:04][0m [97m[43m WAR [0m Error while pinging UI service: rpc error: code = DeadlineExceeded desc = context deadline exceeded, state: READY

[2m[2023-02-13 10:55:04][0m [97m[104m IMP [0m Got signal: terminated
[2m[2023-02-13 10:55:05][0m [97m[41m ERR [0m getting notifications: rpc error: code = Unavailable desc = error reading from server: read unix @->/tmp/osui.sock: read: connection reset by peer <nil>
[2m[2023-02-13 10:55:10][0m [97m[43m WAR [0m queue stuck, closing by timeout
[2m[2023-02-13 10:55:10][0m [97m[43m WAR [0m Queue.destroy(), nfq_close() not closed: -1

[2m[2023-02-13 11:47:40][0m [97m[104m IMP [0m Start writing logs to /var/log/opensnitchd.log
[2m[2023-02-13 11:47:40][0m [97m[41m ERR [0m eBPF Failed to load /etc/opensnitchd/opensnitch.o: open /etc/opensnitchd/opensnitch.o: no such file or directory
[2m[2023-02-13 11:47:40][0m [97m[43m WAR [0m error starting ebpf monitor method: open /etc/opensnitchd/opensnitch.o: no such file or directory
[2m[2023-02-13 11:47:40][0m [97m[43m WAR [0m Unable to set new process monitor method from disk: open /etc/opensnitchd/opensnitch.o: no such file or directory`

--
Opensnitch-ui was originally using proc for process monitor method, now it uses ebpf as default after reinstall

**Comment by grawlinson** [comment] 2023-02-14 00:07
Hi, this is a dupe of #833

**Comment by gustavo-iniguez-goya** [comment] 2023-02-14 01:14
Thank you @dissona for reporting this issue.

It has been already solved by @grawlinson :heart: , but it may take some time to propagate to Manjaro.

**Closed by gustavo-iniguez-goya** 2023-02-14 01:14 UTC
