### ISSUE TITLE
Delay during shutdown

### ISSUE THREAD

**Issue by BobSquarePants** [evilsocket/opensnitch#677] opened 2022-06-23 10:21 UTC
I installed OpenSnitch + GUI on a fresh devuan.

it seem that now when I click on shutdown (xfce4-session-logout)
![logout](https://user-images.githubusercontent.com/23012674/175276892-25c06a77-ec36-416b-9800-08cdb6022430.png)
that I get a delay (nothing happen) for ~8 second and finally the system start the shutdown process..

a `$ su; poweroff` do not encounter the problem :open_mouth: 

---

- OpenSnitch version :[v1.6.0-rc.1](https://github.com/evilsocket/opensnitch/releases/tag/v1.6.0-rc.1)
- OS: Devuan
- Window Manager: XFCE
- Kernel version: Linux 5.10.0-9-amd64 .1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux

**Comment by gustavo-iniguez-goya** [comment] 2022-06-23 11:46
Thank you! I'll also try to reproduce it. 

Also, having logs level to DEBUG: 1) reboot and write down the date, 2) post the logs + date of reboot
That way it'll be easier to analyze the delay.

**Comment by gustavo-iniguez-goya** [comment] 2022-06-23 14:41
I'm not able to reproduce this problem. I Installed devuan to disk + update devuan + reboot + install opensnitch + enable fw + shutdown, but I see no delay.

Have you ever had this problem before?

I suggest to do the following:
 - Disable /etc/nftables.conf (empty it, comment out everything, disable sysvinit script, etc..)
 - Disable OpenSnitch system firewall.
 - Shutdown and see if there's any delays.

Are there delays? -> debug what is causing that behaviour.

No delays?
 - Boot
 - Enable OpenSnitch system firewall.
 - Shutdown and see if there's any delays.

**Comment by BobSquarePants** [comment] 2022-06-24 05:33
I discover that the problem is coming from the GUI.
To close the GUI it take ~6 sec (with or without opensnitch enabled)

When the GUI is close no delay to shutdown the system.

I will try now on another devuan to see if the same problem occur.

btw which log would you want (path) ?  **/var/log/debug** ?

**Comment by gustavo-iniguez-goya** [comment] 2022-06-24 07:53
Thank you @BobSquarePants ! 

Ok, the delay closing the GUI is known. I'll try to improve it.

By the way, on Devuan you may need to exclude or allow connections to the port 6000, which is what Slim uses. Otherwise you may be unable to log in, showing only a black window. 

* System fw icon -> Exclude service -> port 6000 or 
* New rule ->[x] From this executable: /usr/bin/slim

In general, it's a good idea to allow connections to localhost -> New rule -> [x] To this IP/Network: LAN

>btw which log would you want (path) ? /var/log/debug ? 

/var/log/opensnichd.log

**Comment by BobSquarePants** [comment] 2022-06-24 08:01
> Ok, the delay closing the GUI is known. I'll try to improve it.

:+1: 

no worries for the port 6000 I'm not using any login manager.. no use.. `apt purge slim`

**Closed** 2022-06-24 11:26 UTC

**Comment by gustavo-iniguez-goya** [comment] 2022-06-24 11:30
Fixed @BobSquarePants . If you want to test it you can grab these files from the latest commit:
https://github.com/evilsocket/opensnitch/commit/f54eb789ffec4449b48131a076dd65cf95561aad

https://raw.githubusercontent.com/evilsocket/opensnitch/f54eb789ffec4449b48131a076dd65cf95561aad/ui/opensnitch/service.py
https://raw.githubusercontent.com/evilsocket/opensnitch/f54eb789ffec4449b48131a076dd65cf95561aad/ui/opensnitch/nodes.py
https://raw.githubusercontent.com/evilsocket/opensnitch/f54eb789ffec4449b48131a076dd65cf95561aad/ui/bin/opensnitch-ui

and replaced them with the installed ones:
 - service.py , nodes.py -> /usr/lib/python3/dist-packages/opensnitch
 - opensnitch-ui -> /usr/bin/

**Comment by BobSquarePants** [comment] 2022-06-26 10:54
Hi @gustavo-iniguez-goya ,

I've tried those new files.

indeed when right clicking on the menu icon (I don't know the correct name) then **Close**.
![fast](https://user-images.githubusercontent.com/23012674/175810639-2126d478-f94c-4662-a887-fee767b3d437.png)

it close instantly instead of waiting ~7sec. :partying_face: 

poweroff the system when the GUI has been closed like this, do not take any more delay. !

--

but if I don't close the GUI by this menu (right click, Close), then the poweroff (by GUI)
![logout](https://user-images.githubusercontent.com/23012674/175276892-25c06a77-ec36-416b-9800-08cdb6022430.png)
is still impacted by this ~7 sec delay.

**Comment by gustavo-iniguez-goya** [comment] 2022-06-26 12:25
mmh, ok, I'll investigate that problem

**Comment by gustavo-iniguez-goya** [comment] 2022-06-26 22:50
reproduced, but unfortunately no idea on how to fix it. I've tried out several things but none of them worked.

**Comment by BobSquarePants** [comment] 2022-06-27 04:58
Thanks @gustavo-iniguez-goya ,

A workaround until resolution could be to launch a command or script at shutdown that emulate/call the same action as close ->
![fast](https://user-images.githubusercontent.com/23012674/175810639-2126d478-f94c-4662-a887-fee767b3d437.png)

**Comment by gustavo-iniguez-goya** [comment] 2022-06-30 18:50
It seems that XFCE sends a SIGHUP to the running processes of the current session when shutting down/logging out.
Capturing that signal and quitting gracefully seems to solve this problem, although not always.

Anyway, the signal SIGHUP is commonly used to reload configuration for example, so I need to test it on others DE to see how it behaves.

**Comment by gustavo-iniguez-goya** [comment] 2022-06-30 23:56
@BobSquarePants could you test these 2 files?
[service.py.txt](https://github.com/evilsocket/opensnitch/files/9024096/service.py.txt) -> rename to service.py -> move to -> /usr/lib/python3/dist-packages/opensnitch/service.py
[opensnitch-ui.txt](https://github.com/evilsocket/opensnitch/files/9024099/opensnitch-ui.txt) -> rename to opensnitch-ui + chmod a+x -> move to -> /usr/bin/

Or just apply the following changes.

```diff
--- opensnitch/service.py	2022-06-24 13:22:00.389692826 +0200
+++ lib/python3.9/site-packages/opensnitch/service.py	2022-07-01 01:45:17.207258636 +0200
@@ -4,6 +4,7 @@
 from threading import Thread, Lock, Event
 import grpc
 import os
+import signal
 import sys
 import json
 
@@ -40,6 +41,7 @@
     def __init__(self, app, on_exit):
         super(UIService, self).__init__()
 
+        signal.signal(signal.SIGHUP, self.signal_handler)
 
         self.MENU_ENTRY_STATS = QtCore.QCoreApplication.translate("contextual_menu", "Statistics")
         self.MENU_ENTRY_FW_ENABLE = QtCore.QCoreApplication.translate("contextual_menu", "Enable")
@@ -110,6 +112,10 @@
         if self._cfg.getBool(Config.DEFAULT_DB_PURGE_OLDEST):
             self._start_db_cleaner()
 
+    def signal_handler(self, signum, frame):
+        print("Signal {0} received, closing".format(signum))
+        self._on_close()
+
     # https://gist.github.com/pklaus/289646
     def _setup_interfaces(self):
         namestr, outbytes = Utils.get_interfaces()

```

```diff
--- a/ui/bin/opensnitch-ui
+++ b/ui/bin/opensnitch-ui
@@ -89,9 +89,6 @@ if __name__ == '__main__':
     else:
         server.add_insecure_port(args.socket)
 
-    # https://stackoverflow.com/questions/5160577/ctrl-c-doesnt-work-with-pyqt
-    signal.signal(signal.SIGINT, signal.SIG_DFL)
-
     try:
         # print "OpenSnitch UI service running on %s ..." % socket
         server.start()
```
