### ISSUE TITLE
Keyboard entries are not detected

### ISSUE THREAD

**Issue by pardub** [evilsocket/opensnitch#734] opened 2022-09-05 09:23 UTC
The keyboard entries are not detected  when I type in the "Filter" field or if I want to add a new rule in the filed "Name".
I reinstalled Fedora 35 and even install it on a second laptop and the issue is the same.
When I started typing, maybe 2 or 3 characters are sometimes recognized then it seems the keyboard is not recognized.
I don't see this issue with any other apps at the moment and the keyboard is recognized when I use a different app.
Same issue with Opensnicth 1.5.1 or 1.5.2 even if the dark mode is not installed.

    OpenSnitch version: 1.5.2
    OS: Fedora 35
    Kernel version: 5.19.6-100.fc35.x86_64
    Display Server: Wayland

How I installed Opensnitch?

sudo mkdir -p /opt/opensnitch
cd /opt/opensnitch
sudo wget https://github.com/evilsocket/opensnitch/releases/download/v1.5.2/opensnitch-1.5.2-1.x86_64.rpm
sudo wget https://github.com/evilsocket/opensnitch/releases/download/v1.5.2/opensnitch-ui-1.5.1-1.noarch.f29.rpm
sudo dnf -y localinstall opensnitch-1*.rpm; sudo dnf -y localinstall opensnitch-ui*.rpm
sudo systemctl enable --now opensnitch
sudo systemctl start opensnitch

Opensnitch dark mode installation 
pip3 install grpcio-tools
pip3 install unicode_slugify
pip3 install qt-material

**Comment by gustavo-iniguez-goya** [comment] 2022-09-10 15:58
hey @pardub , I've just reproduced this problem on f35. However typing on the Filter text field works for me, but no on some other text fields. I'll investigate why this behaviour.

**Comment by gustavo-iniguez-goya** [comment] 2022-09-10 16:06
mmh, and now I don't reproduce it... I'll keep testing this since I'm testing another part of the GUI.

**Comment by pardub** [comment] 2022-09-10 16:36
Hi @gustavo-iniguez-goya ,
I had the same issue, it's not permanent.Sometimes, the characters typed from the keyboard are displayed normally, and sometimes it's not.
Thank you for your investigation.

**Comment by gustavo-iniguez-goya** [comment] 2023-06-24 23:14
Closing as it doesn't seem to be related directly to us.

**Closed by gustavo-iniguez-goya** 2023-06-24 23:14 UTC
