### ISSUE TITLE
CPU and memory usage goes up in time

### ISSUE THREAD

**Issue by cccaballero** [evilsocket/opensnitch#236] opened 2019-01-03 15:56 UTC
Installed in Ubuntu 18.04, and the CPU and RAM usage is increasing in time, I think there is a memory leak or something similar.

**Comment by britzke** [comment] 2019-02-12 07:12
I noticed the same on Ubuntu 18.10 with 4GB of RAM. It is taking 60% of it after 24 hours.

**Comment by zero77** [comment] 2019-02-12 12:37
I am getting the same in Ubuntu 18.04.1 but, as a temporary fix i restart the service which helps for a while.

**Comment by CrashTD** [comment] 2019-02-26 13:54
Can confirm on Manjaro (4.19.24). CPU is okay but RAM goes up massive. After a while it cross 2 GB. Makes it unfortunately unusable at the moment.

**Comment by zaen323** [comment] 2019-04-24 05:07
Also the same on Arch Linux (5.0.7-arch1-1-ARCH), opensnitch version: 20181221.365_0316580-1
Did not note down the exact amount of memory usage (sorry), but I think it was about 9GB in a 32GB system.

**Comment by robeastham** [comment] 2019-05-19 09:22
Can confirm - using 6GB after 24hrs on 16GB RAM  Gnome based 18.04.2 install.

**Comment by britzke** [comment] 2019-05-19 11:22
Dös anybody has n idea, where to look for it? May be I do not have to debug the whole code. 

burghard.britzke 
https://britzke.berlin/

**Comment by j-degreef** [comment] 2019-05-25 18:27
This may be of interest : https://medium.freecodecamp.org/how-i-investigated-memory-leaks-in-go-using-pprof-on-a-large-codebase-4bec4325e192.
But personally I'm a bit tired of Google and it's "inventions".

**Comment by gustavo-iniguez-goya** [comment] 2019-06-17 20:02
Hi all,

Could you specifiy if the high CPU usage is caused by the UI? I can help with that I think . Could you post how many rows do you have in each tab when that problem occur?

Regarding the high mem usage, I also experienced it a while back, but for now it's contained. I'm using latest sources from the repo.

**Comment by benjaoming** [comment] 2019-11-18 16:14
I want to confirm that this is an issue related to the daemon / the Go code.

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                            
23228 root      20   0 4389272 2.644g   2908 S  49,7 34,4 465:43.70 opensnitchd   
```

As you can see, there's a memory usage of 2.5 GB... CPU time is constantly around 30-50% of a core.

**Comment by gustavo-iniguez-goya** [comment] 2019-11-18 19:50
Try this branch @benjaoming , and see if you can reproduce it or if it works as expected:
https://github.com/gustavo-iniguez-goya/opensnitch/tree/main

**Comment by gustavo-iniguez-goya** [comment] 2020-12-10 23:34
This should be fixed with latest version.

If it still reproduces, please, open a new issue and post:
- top output showing the process eating up the CPU.
- Apps that may be causing this behaviour (transmission/qbitorrent..).
- Set debug level to DEBUG and post /var/log/opensnitchd.log

**Closed by gustavo-iniguez-goya** 2020-12-10 23:34 UTC
