### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by medoix** [evilsocket/opensnitch#170] opened 2018-04-28 20:28 UTC
1. What is the reason for the stats.ui window being locked on top?
2. Would you be ok with a feature to disable the auto apply in prompt.ui? (LittleSnitch does not auto apply as that seems to defeat the purpose) curious on your thoughts here.
3. I am on HIDPI displays and both stats/prompt windows are squished to the point i cannot click buttons, in Qt i trialed arranging vertically and setting the main window to reisable allows for the content to stretch. I do not have a non 4k display to test how do you suggest proceeding with this?

**Comment by evilsocket** [comment] 2018-04-29 09:59
1. Because when you're using your computer, with many applications being open and with different focuses, if the opensnitch UI doesn't appear on top of everything, chances are you'll just miss it, it'll timeout and the default action will be performed.

2. Yes and no, regardless what the UI decides, the daemon has a time limit within which has to provide an answer to NFQUEUE, so I think it should just be left there in order to avoid confusion (UI without timeout and the daemon with).

3. A screenshot would be a good start.

**Comment by medoix** [comment] 2018-04-29 11:25
1. Totally agree for prompt.ui that is why i only asked about the stats.ui window, leaving the stats.ui window to be open or closed front or back could be useful (to keep an eye on whats going on) but prompts 100% need to be on top for the exact reason you stated.

2. If the client and daemon default to allow everything what is the intended purpose of OpenSnitch from your perspective? I know you can change the default UI behavior to Deny. Is the default daemon timeout you refer to in `daemon/ui/client.go` line 151?

3. The stats window, it is not re-sizable. I was not able to get a grab of the prompt just yet but has similar issue.
![stats](https://user-images.githubusercontent.com/149519/39406037-baa26abe-4bf3-11e8-902c-a3eb3e93dadc.png)

**Comment by evilsocket** [comment] 2018-04-29 14:49
1. Idk i usually keep both to see what's going on, no other particular reasons.
2. The do not allow everything, they allow what doesn't match the rules, which has different implications.
3. that's weird, I used it both in 1080 and 4K HiDPI and didn't experience that behaviour, what DE are you using?

**Comment by sh2ka** [comment] 2018-05-11 04:46
What is the reason of keeping OpenSnitch Network Statistics window to be of fixed size? On large screens it would be nice to maximize window and see stats without scrolling (I mean General tab).

**Comment by sh2ka** [comment] 2018-05-11 05:34
2. What happens when UI is not running and a new connection trying to be established and that is doesn't appear in rules? Will it be blocked?
3. I tried to connect to a site using "telnet <site> <port>" and connected without any problems. OpenSnitch haven't blocked it. The question is "Why?". And could you reproduce the same?

**Comment by gustavo-iniguez-goya** [comment] 2020-12-11 00:31
This should be fixed with latest version.

**Closed by gustavo-iniguez-goya** 2020-12-11 00:31 UTC
