### ISSUE TITLE
Feature Request: Always on top popup alarts

### ISSUE THREAD

**Issue by MainTomato** [evilsocket/opensnitch#446] opened 2021-06-26 21:13 UTC
This would be useful when games open In full-screen by default and request Internet access

**Comment by gustavo-iniguez-goya** [comment] 2021-06-28 22:58
Hi @MainTomato !

Do you mean to not show the pop-ups if a game (or video) is in full-screen? Yeah, ok, we could have an option for it. But we need to investigate how to detect full-screen mode.

**Comment by MainTomato** [comment] 2021-06-29 02:18
Not quite, I actually WANT the pop-ups to display over the game so I can easily manage the connections the game Is making. 

A setting for both choices would be good there might be someone that doesn't want any pop-ups during gameplay.

Some programs might automatically start In fullscreen and sometimes It's awkward to manage.

**Comment by gustavo-iniguez-goya** [comment] 2021-07-07 10:48
oops, I thought that the pop-ups were already been displayed above fullscreen windows, like videoplayers and others.
I haven't tested it with video games though.

The pop-ups have the flag QtCore.Qt.WindowStaysOnTopHint set, which means: _Informs the window system that the window should stay on top of all other windows._

I'll try to reproduce it with video games.

**Comment by gustavo-iniguez-goya** [comment] 2021-07-07 18:45
I'll use the usual excuse: "it works for me" O:)

![image](https://user-images.githubusercontent.com/2742953/124812489-f596f700-df63-11eb-9c19-98ccfb8cc5d7.png)


Did you reproduce it with Steam or something like that? could you tell us the game?

**Comment by gustavo-iniguez-goya** [comment] 2021-07-22 10:59
closed as "works for me". If you still have this problem with latest version https://github.com/evilsocket/opensnitch/releases/tag/v1.4.0-rc.3 reopen the issue, providing information about in what game/app the pop-ups are not showing up when they're in fullscreen.

Also, close the GUI and launch it from a terminal (`$ opensnitch-ui`) and post any errors that appear.

**Closed by gustavo-iniguez-goya** 2021-07-22 10:59 UTC

**Comment by MainTomato** [comment] 2021-08-12 17:54
This normally happens In full screen Wine/Proton apps, was just wondering If there's a way to make It more aggressive. For example sometimes a game won't allow you to display a Window on top of It If It's full screen no matter how many times you alt-tab. With Native Linux apps there's a lot less awkwardness. Idk If there's a real way to fix this
