### ISSUE TITLE
OpenSnitch UI: KeyError (uid not found)

### ISSUE THREAD

**Issue by wickedsp1d3r** [evilsocket/opensnitch#185] opened 2018-08-04 06:22 UTC
Hi,

Yesterday I installed OpenSnitch with the steps mentioned.
The service is running and it starts automatically on reboot.
However I have problems starting the UI.

When I issue `opensnitch-ui` to start the UI, I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/opensnitch/dialogs/stats.py", line 204, in _on_update_triggered
    by_users["%s (%s)" % (pwd.getpwuid(int(uid)).pw_name, uid)] = hits
KeyError: 'getpwuid(): uid not found: 62582'
Aborted
```
I have no idea what causes this (other than `/etc/passwd` does not have this uid [but why it should have?]) and where to go for a solution.

Any help is highly appreciated!
Thanks.

**Comment by Northern-Lights** [comment] 2018-08-16 05:28
Just jotting down some notes, here...
1. The uid 62582 looks more like a PID rather than a UID
- In stats.py:204, `self._stats.by_uid` is from the definition at ui.proto:31, obviously meant to be a user ID
- Searching for "ByUID" in the daemon code leads us to stats.go:149 which uses `con.Entry.UserId`
- `con` is a `connection.Connection` defined at connection.go:18
- It has an `Entry` field defined at entry.go:7, with a constructor defined below it
- The constructor is only used at parse.go:77
- The data fed to the constructor comes from parsing out `/proc/net/%s`, where I'm assuming `%s` is either tcp, udp, or whatever other protocol is being filtered

My guess is that somehow, the parsing is failing, possibly due to a missing field or some other factor.  I see that all of the columns in my tcp and udp entries line up, and I am not able to reproduce the original issue.  However, looking at the data in my entries, it's plausible that the `62852` number is coming from the `inode` column, if parsing is, indeed, the issue.

**Comment by OderDochNicht** [comment] 2018-08-16 08:46
After cleaning up the issue 184 Northern-Lights referenced above:
 
Shortly after starting opensnitch-ui I get:
`opensnitch-ui 
E0816 10:34:07.664790433   16327 tcp_server_posix.cc:210]    Failed accept4: Zu viele offene Dateien
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/opensnitch/dialogs/stats.py", line 204, in _on_update_triggered
KeyError: 'getpwuid(): uid not found: 114'
Abgebrochen
`
uid 114:
` egrep 114 /etc/passwd
pulse:x:110:114:PulseAudio daemon,,,:/var/run/pulse:/usr/sbin/nologin
colord:x:114:121:colord colour management daemon,,,:/var/lib/colord:/usr/sbin/nologin`

Translation:
Zu viele offene Dateien: Too many open files
Abgebrochen: Aborted

**Comment by Northern-Lights** [comment] 2018-08-17 05:26
I can't see anything related to a UID 114 from your output...  I am not sure then what the issue might be.

My PR (#188 ) handles the exception so that the UI should be able to proceed showing `(error)` where the bad UID is occurring.  I am not able to test it since I am not seeing the issue myself, but it should at least allow you to run the UI.

To dig deeper to find the problem, you may be able to import `"github.com/evilsocket/opensnitch/daemon/log"` and instrument the `Parse()` function in parse.go:70, maybe saving `scanner.Text()` in a variable and printing it to the log.  That might help us nail down where the UI is getting the bad UID.

**Comment by OderDochNicht** [comment] 2018-08-24 08:53
OK, the problem solved itself - in a way :-)
Because of a wine issue I purged libfreetype6 (not recommended - apt will deinstall all dependencies and that's are a lot. Especially gui-related ones.)
After a reinstall of most of the purged packets (xfce4, libreoffice, recoll, ocrmypdf, ...) and a reboot opensnitch works without issues.

So probably an issue from some leftover libs?

apt now recommends an autoremove of these packages:
`docbook-xml espeak-ng-data evince-common fonts-font-awesome fonts-roboto-slab gir1.2-atk-1.0 gir1.2-gst-plugins-base-1.0
  gir1.2-gstreamer-1.0 gnome-desktop3-data gstreamer1.0-alsa libatk-adaptor libbrlapi0.6 libchm1 libdbusmenu-glib4 libdotconf0
  libdv4 libept1.5.0 libespeak-ng1 libglib-perl libid3tag0 libiec61883-0 libjs-modernizr libjs-sphinxdoc libjs-underscore
  libjsoncpp1 libkchart2-l10n libkf5khtml-data libkpathsea6 libmarkdown2 libmediainfo0v5 libpcaudio0 libqt4-dbus libqt4-network
  libqt4-script libqt4-sql libqt4-sql-mysql libqt4-test libqt4-xml libqt4-xmlpatterns libqtassistantclient4 libqtcore4 libqtdbus4
  librarian0 libsdl2-2.0-0 libsonic0 libspeechd2 libspnav0 libstemmer0d libtar0 libtinyxml2-6a libu2f-udev libvkd3d1 libzen0v5
  libzip4 mobile-broadband-provider-info python3-brlapi python3-dbus.mainloop.qt python3-feedparser python3-gst-1.0 python3-louis
  python3-musicbrainzngs python3-mutagen python3-pyinotify python3-sip python3-speechd qdbus qtchooser qtcore4-l10n rarian-compat
  sgml-base sgml-data sound-icons speech-dispatcher speech-dispatcher-audio-plugins speech-dispatcher-espeak-ng
  sphinx-rtd-theme-common xml-core`

Perhaps the issue is with one of those packages.

**Comment by gustavo-iniguez-goya** [comment] 2020-12-11 00:25
This problem should be fixed with latest packages.

**Closed by gustavo-iniguez-goya** 2020-12-11 00:25 UTC
