### ISSUE TITLE
UI does not work in Ubuntu 20.04

### ISSUE THREAD

**Issue by pabloab** [evilsocket/opensnitch#678] opened 2022-06-25 00:18 UTC
OpenSnitch (service and UI) was running fine on my Ubuntu 20.04, v1.5.0. Not sure why now UI crush with (service status is fine):

```
$ /bin/sh -c 'pkill -15 opensnitch-ui; opensnitch-ui'
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 23, in <module>
    from opensnitch.service import UIService
  File "/usr/lib/python3/dist-packages/opensnitch/service.py", line 13, in <module>
    from opensnitch import ui_pb2
  File "/usr/lib/python3/dist-packages/opensnitch/ui_pb2.py", line 32, in <module>
    _descriptor.EnumValueDescriptor(
  File "/home/pablo/.local/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```
Doesn't seem related to issue #647 (`pip3 install --ignore-installed grpcio` doesn't solve the issue). Tried installing last stable version (python3-opensnitch-ui v1.5.1-1) without luck (no errors through the installation).

Using Ubuntu 20.04.4 LTS, GNOME Shell, Linux  5.4.0-120-generic #136-Ubuntu SMP Fri Jun 10 13:40:48 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux. python3-protobuf v3.6.1.3-2ubuntu5.

To reproduce, run `/bin/sh -c 'pkill -15 opensnitch-ui; opensnitch-ui'` on a terminal.

**Comment by gustavo-iniguez-goya** [comment] 2022-06-25 09:49
Hi @pabloab ,

Could you post your python3-protobuf installed version? `$ dpkg -l 'python3-protobuf'`

Also, could you launch the GUI as follow?:
`$ export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python opensnitch-ui`

Thak you for reporting this issue! I'll try to reproduce it to try several things before bothering you with more tests.

**Comment by gustavo-iniguez-goya** [comment] 2022-06-25 12:17
On a fresh ubuntu 20.04 installation, with python3-protobuf 3.6.1 (3.6.1.3-2ubuntu5) and python3-grpcio (1.16.1-1ubuntu5) 1.16.1 the GUI works fine as expected.

> was running fine on my Ubuntu 20.04, v1.5.0. Not sure why now UI crush 

mmh, have you installed or upgraded recently anything?

**Comment by pabloab** [comment] 2022-06-26 19:53
> Could you post your python3-protobuf installed version? `$ dpkg -l 'python3-protobuf'`

python3-protobuf 3.6.1.3-2ubuntu5

> Also, could you launch the GUI as follow?: `$ export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python opensnitch-ui`

    bash: export: `opensnitch-ui': not a valid identifier

`$ which python` -> /usr/bin/python -> /etc/alternatives/python -> /usr/bin/python3. `$ python --version`: Python 3.8.10. 

> mmh, have you installed or upgraded recently anything?

Beside just regular apt update/upgrade, I had some issues between guake (build from source) and python libraries installed through brew. 

> and python3-grpcio (1.16.1-1ubuntu5) 1.16.1 

I installed python3-grpcio (apt) and now it's working. I uninstalled it a couple of days ago trying to fix this issue (maybe based on [this comment](https://github.com/evilsocket/opensnitch/issues/647#issuecomment-1113282664)), so it is unclear to me what happened.

**Comment by gustavo-iniguez-goya** [comment] 2022-06-26 20:40
:tada:  :)

**Comment by pabloab** [comment] 2022-06-27 06:09
A regular `apt autoremove` removed python3-protobuf (only). After that, `pkill -15 opensnitch-ui; opensnitch-ui` crash with [the same first stack trace](https://github.com/evilsocket/opensnitch/issues/678#issue-1284377871). Installed python3-protobuf again immediately, but it stills crash the same way. 
```
$ dpkg -l | egrep "python3-protobuf|python3-grpcio" | awk '{print $2" "$3}'; pkill -15 opensnitch-ui; opensnitch-ui
python3-grpcio 1.16.1-1ubuntu5
python3-protobuf 3.6.1.3-2ubuntu5
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 23, in <module>
...
```

**Comment by gustavo-iniguez-goya** [comment] 2022-06-30 18:46
@pabloab see if you have any python3-protobuf or python3-grpcio locally installed, either in your home: `~/.local/lib/python*` or globally `/usr/local/lib/python*`

If you have any of those packages installed in those directories remove them with pip and try again. It looks like a compatbility problem between installed versions.

**Comment by gustavo-iniguez-goya** [comment] 2022-07-08 15:19
closing, follow last comment to address this problem.

**Closed by gustavo-iniguez-goya** 2022-07-08 15:19 UTC

**Comment by pabloab** [comment] 2022-12-01 03:20
`ls -lahR ~/.local/lib/python* /usr/local/lib/python* | egrep "python3-protobuf|python3-grpcio"` didn't return anything, but today start working. `grep upgrade /var/log/dpkg.log | grep py` doesn't return anything either. 

Maybe not related, but I recently fix an issue with `locale` command. Was using `/home/linuxbrew/.linuxbrew/bin/locale` instead of the one it comes with libc-bin package. [Homebrew](https://brew.sh/) were adding its stuff in `$PATH`, so it has priority, and maybe its glibc version conflict with standard one.
