### ISSUE TITLE
Need some explanations.

### ISSUE THREAD

**Issue by molitona** [evilsocket/opensnitch#435] opened 2021-06-14 13:29 UTC
Hi, I've read your docs and I've have some questions to you if you don't mind.  

I'm using opensnitch 1.3.6 (I've noticed that git version on AUR don't block connections (I'm prompted to accept/deny) and connection is made... so I switched to the stable version)

1- Does opensnitch is always verifying the source of the made connection (firefox, telegram, systemd-resolve,...) in addition to destination criterias check ?

2- I've noticed when I don't click that "+" button, opensnitch passes all connections from a program to any ip,port,tcp/udp without prompting me for each one, e.g. 

from operator_data:

/usr/lib/firefox/firefox

So when I selected what's behind "+" button, now it verifies dest.{ip|host} / dest.port / process.path / user.id , e.g:

from operator_data:

[{"type": "simple", "operand": "dest.ip", "data": "52.41.140.15"}, {"type": "simple", "operand": "dest.port", "data": "443"}, {"type": "simple", "operand": "process.path", "data": "/usr/lib/firefox/firefox"}]

am I right ? and what's the risk from not checking by user.id also ?

3- I can't change pop-up position, is there any workaround ?

![gg](https://user-images.githubusercontent.com/35532337/121900074-eb932700-cd1c-11eb-80ef-9b6e254376c0.png)

4- Can I get advanced view by default without clicking "+" button ?

5- Does even if the connection elements (ip,port,process) are the same and protocol(tcp,udp) is changed then I'm prompted with a pop-up no matter if it's simple or list filter ?

6- Can I only make one connection as prior to others ? as there is no numbers to choose priority order ?

Thanks!

**Comment by gustavo-iniguez-goya** [comment] 2021-06-14 14:45
> I'm using opensnitch 1.3.6 (I've noticed that git version on AUR don't block connections (I'm prompted to accept/deny) and connection is made... so I switched to the stable version)

You need to change the default policy to Deny: Preferences -> Nodes -> Default Action: Deny.

It'll be fixed soon for v1.4.x .

> 1- Does opensnitch is always verifying the source of the made connection (firefox, telegram, systemd-resolve,...) in addition to destination criterias check ?

It depends on the rule. If you set `[x] From this executable` then yes, the source of the connection is checked. 

> 2- I've noticed when I don't click that "+" button, opensnitch passes all connections from a program to any ip,port,tcp/udp without prompting me for each one, e.g. 
> (...) am I right ? and what's the risk from not checking by user.id also ?

Yes, you're right. the default configuration for newly outgoing connections is to deny everything from the executable that opened the connection. 

The rest of the options are to restrict in more detail what an application can do. Say for example that you want to allow chrome to connect only to ports 80 and 443, because you know, that's the common ports to surf the web.

If an extension or website tries to establish a connection on a different port, OpenSnitch will warn you about it:
https://github.com/gustavo-iniguez-goya/opensnitch/issues/21

On the same manner, restricting by user.id ensures that only your user is able to use chrome (or other executable). 

Think of this like: "I need to let chrome use ports 80 and 443 from UserID XXXX, but warn me if it tries to use another port or another UserID" (because that's something unusual and I want to know about it).

> 3- I can't change pop-up position, is there any workaround ?
> 4- Can I get advanced view by default without clicking "+" button ?
> 6- Can I only make one connection as prior to others ? as there is no numbers to choose priority order ?

Use opensnitch-git from AUR repository :-) , those issues are not fixed on 1.3.x version, and you'll help us to test v1.4.x ! :rocket: 

For the 6th: https://github.com/evilsocket/opensnitch/wiki/Rules-examples

> 5- Does even if the connection elements (ip,port,process) are the same and protocol(tcp,udp) is changed then I'm prompted with a pop-up no matter if it's simple or list filter ?

Please rephrase the sentence! I didn't understand it.

**Comment by molitona** [comment] 2021-06-14 18:06
> You need to change the default policy to Deny: Preferences -> Nodes -> Default Action: Deny.
> 
> It'll be fixed soon for v1.4.x .

Fine, it's fixed.

> It depends on the rule. If you set [x] From this executable then yes, the source of the connection is checked.

1.1- So, you mean rules are checked in alphabetical order and then if 2 or more rules have priority then alphabetical order will decide which one will be applied first. ?
1.2- And, I think on every connection the executable who made it should be verified (I mean if it is really firefox who requested access to 5.6.7.8 port 443 and not opera e.g. ), because you said "It depends on the rule" and I didn't get it why ?)

> Use opensnitch-git from AUR repository :-) , those issues are not fixed on 1.3.x version, and you'll help us to test v1.4.x ! 🚀
For sure, I switched again to it.

> Yes, you're right. the default configuration for newly outgoing connections is to deny everything from the executable that opened the connection.
> 
> The rest of the options are to restrict in more detail what an application can do. Say for example that you want to allow chrome to connect only to ports 80 and 443, because you know, that's the common ports to surf the web.
> 
> If an extension or website tries to establish a connection on a different port, OpenSnitch will warn you about it:
> gustavo-iniguez-goya#21
> 
> On the same manner, restricting by user.id ensures that only your user is able to use chrome (or other executable).
> 
> Think of this like: "I need to let chrome use ports 80 and 443 from UserID XXXX, but warn me if it tries to use another port or another UserID" (because that's something unusual and I want to know about it).
> 

Great explanation, thanks!

> Please rephrase the sentence! I didn't understand it.
I mean if X is accessing x.x.x.x on port xx with TCP it is another connection from accessing it on UDP. Its obvious, thanks.

++++ I noticed that counter blocks at 98 when it's configured with 99 as value only in advanced view mode!

++Please, I know that opensnitch uses iptables, I tried to see configured rules with "iptables --list" to no avail, so where can I see them ? (not talking about rules in GUI)

**Comment by molitona** [comment] 2021-06-14 19:05
Also, If you don't mind.
I configured permanent rules with GUI and I'm not seeing them under /etc/opensnitchd/rules, this directory is always empty and when I reboot I lost them !

**Comment by gustavo-iniguez-goya** [comment] 2021-06-14 23:32
> I configured permanent rules with GUI and I'm not seeing them under /etc/opensnitchd/rules, this directory is always empty and when I reboot I lost them !

That's actually really strange! do you have more files under `/etc/opensnitchd/`? like `default-config.json` and `system-fw.json` ?
Is there any errors in the log `/var/log/opensnitchd.log`?

> 1.1- So, you mean rules are checked in alphabetical order and then if 2 or more rules have priority then alphabetical order will decide which one will be applied first. ?

Yes, that's it. Well, the contrary, rules are checked in alphabetical order first, then if a rule has priority or has Action: Deny, that's what decides which one will be applied.

> 1.2- And, I think on every connection the executable who made it should be verified (I mean if it is really firefox who requested access to 5.6.7.8 port 443 and not opera e.g. ), because you said "It depends on the rule" and I didn't get it why ?)

Yeah, I mean, if you create a rule to allow chrome or firefox with the option `[x] From this executable" it'll always be verified.
For example, if you set `[x] From this executable: /usr/lib/firefox/firefox` all connections opened by this binary will be allowed, but if Opera tries to establish a new connection, OpenSnitch will ask you to allow or deny it. 

You can also configure the pop-ups default target, i.e., how new rules will be created (or how new outgoing connections will be filtered). The default option is to Deny connections by executable path, but you can change it Preferences -> UI -> Default target (as well as "Filter connections also by").

> +Please, I know that opensnitch uses iptables, I tried to see configured rules with "iptables --list" to no avail, so where can I see them ? (not talking about rules in GUI)

There should be only 2 rules, one in the filter table and another one in the mangle table:

    iptables -L INPUT
    iptables -t mangle -L OUTPUT

**Comment by molitona** [comment] 2021-06-15 09:21
> That's actually really strange! do you have more files under /etc/opensnitchd/? like default-config.json and system-fw.json ?
> Is there any errors in the log /var/log/opensnitchd.log?

Yeah, I have those 2 files mentioned above and an empty rules folder (same problem occurred with v1.3.6 and the git one).

> Yes, that's it. Well, the contrary, rules are checked in alphabetical order first, then if a rule has priority or has Action: Deny, that's what decides which one will be applied.

Fine, thanks.

Yeah, I mean, if you create a rule to allow chrome or firefox with the option [x] From this executable" it'll always be verified. For example, if you set [x] From this executable: /usr/lib/firefox/firefox` all connections opened by this binary will be allowed, but if Opera tries to establish a new connection, OpenSnitch will ask you to allow or deny it.

> You can also configure the pop-ups default target, i.e., how new rules will be created (or how new outgoing connections will be filtered). The default option is to Deny connections by executable path, but you can change it Preferences -> UI -> Default target (as well as "Filter connections also by").

Fine, thanks.

> There should be only 2 rules, one in the filter table and another one in the mangle table:
> iptables -L INPUT
> iptables -t mangle -L OUTPUT

They don't show anything!

**Comment by gustavo-iniguez-goya** [comment] 2021-06-15 10:19
> Yeah, I have those 2 files mentioned above and an empty rules folder (same problem occurred with v1.3.6 and the git one).

Can you change log level to DEBUG (Preferences -> Nodes -> Log level), monitor `/var/log/opensnitchd.log` , create a new rule with `Duration: always` and see if it outputs any error?

You can also right-click on a rule and change the Duration from the contextual menu.

Post the log here please.

> They don't show anything!

what about. `nft list ruleset` ?

**Comment by molitona** [comment] 2021-06-15 11:07
> what about. nft list ruleset ?
Yeah, it there is an output (I made this rule only to test). I forget to inform you that I've replaced iptables with nftables one day for specific program to work (but, the problem which leads me to forget is that binary name is still iptables even manual, strange!)

table ip opensnitch-filter {
	chain input {
		type filter hook input priority filter; policy accept;
		udp sport 53 queue num 0 bypass
	}
}
table ip6 opensnitch-filter {
	chain input {
		type filter hook input priority filter; policy accept;
		udp sport 53 queue num 0 bypass
	}
}
table ip opensnitch-mangle {
	chain output {
		type route hook output priority mangle; policy accept;
		ct state related,new queue num 0 bypass
	}
}
table ip6 opensnitch-mangle {
	chain output {
		type route hook output priority mangle; policy accept;
		ct state related,new queue num 0 bypass
	}
}

> Can you change log level to DEBUG (Preferences -> Nodes -> Log level), monitor /var/log/opensnitchd.log , create a new rule with Duration: always and see if it outputs any error?
> 
> You can also right-click on a rule and change the Duration from the contextual menu.
> 
> Post the log here please.

[2021-06-15 11:03:32]  IMP  Start writing logs to /var/log/opensnitchd.log
[2021-06-15 11:03:32]  ERR  Error parsing configuration /etc/opensnitchd/default-config.json: unexpected end of JSON input
[2021-06-15 11:03:32]  IMP  Start writing logs to /var/log/opensnitchd.log
[2021-06-15 11:04:08]  INF  [notification] change rule: allow-until-restart-list-usr-lib-firefox-firefox-149-112-112-112-443-1000: if(list is '[{"type": "simple", "operand": "process.path", "data": "/usr/lib/firefox/firefox", "sensitive": false}, {"type": "simple", "operand": "dest.port", "data": "443", "sensitive": false}, {"type": "simple", "operand": "dest.ip", "data": "149.112.112.112", "sensitive": false}, {"type": "simple", "operand": "user.id", "data": "1000", "sensitive": false}]'){ deny until restart } 1623755048992941
[2021-06-15 11:04:08]  DBG  Operator compiled: list is '[{"type": "simple", "operand": "process.path", "data": "/usr/lib/firefox/firefox", "sensitive": false}, {"type": "simple", "operand": "dest.port", "data": "443", "sensitive": false}, {"type": "simple", "operand": "dest.ip", "data": "149.112.112.112", "sensitive": false}, {"type": "simple", "operand": "user.id", "data": "1000", "sensitive": false}]'
[2021-06-15 11:04:08]  DBG  Operator compiled: process.path is '/usr/lib/firefox/firefox'
[2021-06-15 11:04:08]  DBG  Operator compiled: dest.port is '443'
[2021-06-15 11:04:08]  DBG  Operator compiled: dest.ip is '149.112.112.112'
[2021-06-15 11:04:08]  DBG  Operator compiled: user.id is '1000'
[2021-06-15 11:04:28]  INF  [notification] change rule: allow-until-restart-list-usr-lib-firefox-firefox-149-112-112-112-443-1000: if(list is '[{"type": "simple", "operand": "process.path", "data": "/usr/lib/firefox/firefox", "sensitive": false}, {"type": "simple", "operand": "dest.port", "data": "443", "sensitive": false}, {"type": "simple", "operand": "dest.ip", "data": "149.112.112.112", "sensitive": false}, {"type": "simple", "operand": "user.id", "data": "1000", "sensitive": false}]'){ allow always } 16237550684485211
[2021-06-15 11:04:28]  DBG  Operator compiled: list is '[{"type": "simple", "operand": "process.path", "data": "/usr/lib/firefox/firefox", "sensitive": false}, {"type": "simple", "operand": "dest.port", "data": "443", "sensitive": false}, {"type": "simple", "operand": "dest.ip", "data": "149.112.112.112", "sensitive": false}, {"type": "simple", "operand": "user.id", "data": "1000", "sensitive": false}]'
[2021-06-15 11:04:28]  DBG  Operator compiled: process.path is '/usr/lib/firefox/firefox'
[2021-06-15 11:04:28]  DBG  Operator compiled: dest.port is '443'
[2021-06-15 11:04:28]  DBG  Operator compiled: dest.ip is '149.112.112.112'
[2021-06-15 11:04:28]  DBG  Operator compiled: user.id is '1000'
[2021-06-15 11:04:28]  IMP  Ruleset changed due to allow-until-restart-list-usr-lib-firefox-firefox-149-112-112-112-443-1000.json, reloading ...
[2021-06-15 11:04:28]  DBG  Operator compiled: list is '[{"type": "simple", "operand": "process.path", "data": "/usr/lib/firefox/firefox", "sensitive": false}, {"type": "simple", "operand": "dest.port", "data": "443", "sensitive": false}, {"type": "simple", "operand": "dest.ip", "data": "149.112.112.112", "sensitive": false}, {"type": "simple", "operand": "user.id", "data": "1000", "sensitive": false}]'
[2021-06-15 11:04:28]  DBG  Operator compiled: process.path is '/usr/lib/firefox/firefox'
[2021-06-15 11:04:28]  DBG  Operator compiled: dest.port is '443'
[2021-06-15 11:04:28]  DBG  Operator compiled: dest.ip is '149.112.112.112'
[2021-06-15 11:04:28]  DBG  Operator compiled: user.id is '1000'
[2021-06-15 11:04:28]  DBG  Loaded rule from /etc/opensnitchd/rules/allow-until-restart-list-usr-lib-firefox-firefox-149-112-112-112-443-1000.json: allow-until-restart-list-usr-lib-firefox-firefox-149-112-112-112-443-1000: if(list is '[{"type": "simple", "operand": "process.path", "data": "/usr/lib/firefox/firefox", "sensitive": false}, {"type": "simple", "operand": "dest.port", "data": "443", "sensitive": false}, {"type": "simple", "operand": "dest.ip", "data": "149.112.112.112", "sensitive": false}, {"type": "simple", "operand": "user.id", "data": "1000", "sensitive": false}]'){ allow always }

**Comment by gustavo-iniguez-goya** [comment] 2021-06-15 14:42
> I've replaced iptables with nftables one day for specific program to work

Fantastic! I added nftables support a few days ago, so you just confirmed me that it works fine :-)

> ERR Error parsing configuration /etc/opensnitchd/default-config.json: unexpected end of JSON input

This error could indicate that it's empty. Please, verify that it's not empty, and if it's download it from here https://raw.githubusercontent.com/evilsocket/opensnitch/master/daemon/default-config.json

If it's empty it could haven been caused by installing/uninstalling different versions.

> [2021-06-15 11:04:28] DBG Loaded rule from /etc/opensnitchd/rules/allow-until-restart-list-usr-lib-firefox-firefox-149-112-112-112-443-1000.json

According to this log, you should have some *.json files under `/etc/opensnitchd/rules/` , so it seems that "permanent" rules are working fine.

Download `default-config.json` , restart the daemon and try to create new rules with Duration: always, and check that the corresponding .json file is created under `/etc/opensnitchd/rules/`

**Comment by molitona** [comment] 2021-06-15 16:29
> Fantastic! I added nftables support a few days ago, so you just confirmed me that it works fine :-)

Happy to hear that!

> This error could indicate that it's empty. Please, verify that it's not empty, and if it's download it from here https://raw.githubusercontent.com/evilsocket/opensnitch/master/daemon/default-config.json

It's not empty, here is content :
{"Server": {"Address": "unix:///tmp/osui.sock", "LogFile": "/var/log/opensnitchd.log"}, "DefaultAction": "deny", "DefaultDuration": "until restart", "InterceptUnknown": true, "ProcMonitorMethod": "proc", "LogLevel": 0}

> According to this log, you should have some *.json files under /etc/opensnitchd/rules/ , so it seems that "permanent" rules are working fine.
> 
> Download default-config.json , restart the daemon and try to create new rules with Duration: always, and check that the corresponding .json file is created under /etc/opensnitchd/rules/

Oh, no I misunderstood when JSON files are created. I thought even if a rule is marked as "Until reboot" a JSON file will be created and I'll be prompted to accept defined rules in that file again across reboots.

**Comment by gustavo-iniguez-goya** [comment] 2021-06-15 16:32
woah, change this option `"DefaultDuration": "until restart"` to `"once"` in the `default-config.json`.

I think that's the root of the issues you're having.

**Comment by molitona** [comment] 2021-06-15 16:55
What could be a problem with "until reboot" ?
And, please I noticed that protocol is not enforced by default. So, when I accept a connection with TCP the protocol is set to be anything (verified with GUI rule editor).

-------- Original Message --------

**Comment by molitona** [comment] 2021-06-15 18:29
I noticed that JSON file names are quoted when rules contain regexp. Why this behavior ? It caused me an error with rsync command.

![f](https://user-images.githubusercontent.com/35532337/122103866-fb8b3380-ce0e-11eb-9515-7b5bd0e814c8.png)

+I received 3 Unknown connections today one of them from zoom app. So, could you tell me what do you do when receiving them ? (I've already read wiki note about it).

**Comment by gustavo-iniguez-goya** [comment] 2021-06-15 20:06
> I noticed that JSON file names are quoted when rules contain regexp. Why this behavior ?

It's more likely that your shell is quoting it rather than OpenSnitch. Try creating the same file under /tmp: 
    
    $ mkdir /tmp/rulesname
    $ touch "/tmp/rulesname/firefox-TCP-{80|443}.json"
    $ ls -l /tmp/rulesname
    -rw-r--r--. 1 a a 0 jun 15 21:38 'firefox-TCP-{80|443}.json'

> +I received 3 Unknown connections today one of them from zoom app. So, could you tell me what do you do when receiving them ? (I've already read wiki note about it).

Nowadays, as far as I can tell, "Unknown connections" are usually responses from new connections, likely SYN-ACKs or alike.
In other scenarios are connections opened by threads of a process (you can read more about this here #343), but in general, nothing suspicious.

In fact, I've been thinking in change the name of that configuration option to "Debug connections: be warned about bad state connections" or something similar.

**Comment by molitona** [comment] 2021-06-15 21:18
> It's more likely that your shell is quoting it rather than OpenSnitch. Try creating the same file under /tmp:

Yeah, I instigated and the cause if pipe line character "|".

> 
> Nowadays, as far as I can tell, "Unknown connections" are usually responses from new connections, likely SYN-ACKs or alike.
> In other scenarios are connections opened by threads of a process (you can read more about this here #343), but in general, nothing suspicious.
> 
> In fact, I've been thinking in change the name of that configuration option to "Debug connections: be warned about bad state connections" or something similar.

Got it, thanks!

Please, you haven't responded to that reply : https://github.com/evilsocket/opensnitch/issues/435#issuecomment-861667297

**Comment by gustavo-iniguez-goya** [comment] 2021-06-15 22:25
> What could be a problem with "until reboot" ? 

Taken a look at the code... daemon's DefaultDuration is not used, i.e., it's always "once". The DefaultAction on a network packet is always applied once.

**Comment by molitona** [comment] 2021-06-16 09:59
Hi again, another problem with nftables I think.
I noticed today that PING command doesn't work anymore (pinging ip/host failed). So, I disabled all my rules and the problem persist, then I checked "sudo nft list ruleset" and I get the response below no matter if my all rules are enabled/disabled. (That's very strange in case rules are disabled, where are they stored ?) 

> table ip opensnitch-filter {
> 	chain input {
> 		type filter hook input priority filter; policy accept;
> 		udp sport 53 queue num 0 bypass
> 	}
> }
> table ip6 opensnitch-filter {
> 	chain input {
> 		type filter hook input priority filter; policy accept;
> 		udp sport 53 queue num 0 bypass
> 	}
> }
> table ip opensnitch-mangle {
> 	chain output {
> 		type route hook output priority mangle; policy accept;
> 		ct state related,new queue num 0 bypass
> 	}
> }
> table ip6 opensnitch-mangle {
> 	chain output {
> 		type route hook output priority mangle; policy accept;
> 		ct state related,new queue num 0 bypass
> 	}
> }
 
If I disable opensnitch, PING work and the above command doesn't output anything.

**Comment by gustavo-iniguez-goya** [comment] 2021-06-16 11:49
> And, please I noticed that protocol is not enforced by default. So, when I accept a connection with TCP the protocol is set to be anything (verified with GUI rule editor).

Do you mean to be able to select from the pop-ups to filter connections also by protocol?

![image](https://user-images.githubusercontent.com/2742953/122210637-24aad300-cea6-11eb-8a0c-73c36d6a7267.png)

You can take an action on a connection, and later edit the rule to restrict it in more detail.

> And, last question if you don't mind. Is this rule correct ?
> ^(91.108..*)$

Yes, but better like this: `^(91\.108\..*)$`

> I noticed that PING command doesn't work anymore 

Yes, with `DefaultAction: deny` nothing is allowed except the rules defined. But Iwe don't handle ICMP packets, so they're blocked, regardless if you disable the rules.

With iptables there's an ICMP rule that bypasses opensnitch interception (see `/etc/opensnitchd/system-fw.json`) but I haven't modified yet that option to work with nftables. You can test it adding a new rule:
`nft insert rule opensnitch-mangle output icmp type echo-request accept`

I'm working on it.

**Comment by molitona** [comment] 2021-06-16 13:52
> Do you mean to be able to select from the pop-ups to filter connections also by protocol?

Yeah, indeed.

> You can take an action on a connection, and later edit the rule to restrict it in more detail.

That what I'm doing, but I think it would be better to have the protocol option in red color.

> Yes, with DefaultAction: deny nothing is allowed except the rules defined. But Iwe don't handle ICMP packets, so they're blocked, regardless if you disable the rules.

> With iptables there's an ICMP rule that bypasses opensnitch interception (see /etc/opensnitchd/system-fw.json) but I haven't modified yet that option to work with nftables. You can test it adding a new rule:
> nft insert rule opensnitch-mangle output icmp type echo-request accept

Yeah, that command worked fine, but how can I make it persistent ?


Otherwise, do you know other protocols that relies on themselves for Transport like ICMP which are actually blocked by **DefaultAction: deny** ?


And, please how can I see my rules on nftables, your provided command ("sudo nft list ruleset") always give the output below ?

> 
> 
> 
> table ip opensnitch-filter {
> chain input {
> type filter hook input priority filter; policy accept;
> udp sport 53 queue num 0 bypass
> }
> }
> table ip6 opensnitch-filter {
> chain input {
> type filter hook input priority filter; policy accept;
> udp sport 53 queue num 0 bypass
> }
> }
> table ip opensnitch-mangle {
> chain output {
> type route hook output priority mangle; policy accept;
> ct state related,new queue num 0 bypass
> }
> }
> table ip6 opensnitch-mangle {
> chain output {
> type route hook output priority mangle; policy accept;
> ct state related,new queue num 0 bypass
> }
> }

**Comment by gustavo-iniguez-goya** [comment] 2021-06-16 15:30
> Yeah, that command worked fine, but how can I make it persistent ?

If you use Debian (or Ubuntu I guess), you can add the rule to `/etc/nftables.conf`:

	chain output {
		type filter hook output priority 0;
            icmp type {echo-request,echo-reply} accept
	}

then: `service nftables restart`

>  how can I see my rules on nftables, your provided command ("sudo nft list ruleset") always give the output below ?

If there're only opensnitch rules, then it means that you don't have more rules configured.

> And what does the output below do ?

    opensnitch-filter -> input -> udp sport 53 queue num 0 bypass

This rule intercept DNS responses, in order to have a cache of IPs<->domain

    opensnitch-mangle -> output -> ct state related,new queue num 0 bypass

This is the rule that redirects output traffic to OpenSnitch. Only NEW or RELATED connections are intercepted.

**Comment by molitona** [comment] 2021-06-16 17:29
I use Arch. Here is /etc/nftables.conf content (I added what you told me then restart service and restart computer, and ICMP doesn't work).


> table inet filter {
>   chain input {
>     type filter hook input priority 0;
> 
>     # allow established/related connections
>     ct state {established, related} accept
> 
>     # early drop of invalid connections
>     ct state invalid drop
> 
>     # allow from loopback
>     iifname lo accept
> 
>     # allow icmp
>     ip protocol icmp accept
>     meta l4proto ipv6-icmp accept
> 
>     # allow ssh
>     tcp dport ssh accept
> 
>     # everything else
>     reject with icmpx type port-unreachable
>   }
>   chain forward {
>     type filter hook forward priority 0;
>     drop
>   }
>   chain output {
>     type filter hook output priority 0;
>     **icmp type {echo-request,echo-reply} accept**
>   }
> 
> }
> 
> # vim:set ts=2 sw=2 et:
>

**Comment by gustavo-iniguez-goya** [comment] 2021-06-16 18:38
Sorry, this is it:

```
table inet mangle {
    chain output {
        type route hook output priority mangle;
        icmp type {echo-request,echo-reply} accept
    }
}
```

**Comment by molitona** [comment] 2021-06-16 19:15
> #!/usr/bin/nft -f
> # ipv4/ipv6 Simple & Safe Firewall
> # you can find examples in /usr/share/nftables/
> 
> table inet filter {
>   chain input {
>     type filter hook input priority 0;
> 
>     # allow established/related connections
>     ct state {established, related} accept
> 
>     # early drop of invalid connections
>     ct state invalid drop
> 
>     # allow from loopback
>     iifname lo accept
> 
>     # allow icmp
>     ip protocol icmp accept
>     meta l4proto ipv6-icmp accept
> 
>     # allow ssh
>     tcp dport ssh accept
> 
>     # everything else
>     reject with icmpx type port-unreachable
>   }
>   chain forward {
>     type filter hook forward priority 0;
>     drop
>   }
> 
>   chain output {
>     type filter hook output priority 0;
>   }
> 
> table inet mangle {
>     chain output {
>         type route hook output priority mangle;
>         icmp type {echo-request,echo-reply} accept
>     }
> }
> 
> 
> 
> }
> 
> # vim:set ts=2 sw=2 et:

sudo systemctl restart nftables.service
**Job for nftables.service failed because the control process exited with error code.
See "systemctl status nftables.service" and "journalctl -xeu nftables.service" for details**

**Comment by gustavo-iniguez-goya** [comment] 2021-06-16 19:40
Are the other rules defined in nftables.conf loaded?

Maybe you need to enable nftables service? `systemd enable nftables; systemd start nftables` , I have no idea.

**Comment by molitona** [comment] 2021-06-16 22:11
> Are the other rules defined in nftables.conf loaded?

How can I know ?

> Maybe you need to enable nftables service? systemd enable nftables; systemd start nftables , I have no idea.

It worked by doesn't persist across reboots.

**Comment by gustavo-iniguez-goya** [comment] 2021-06-17 12:09
> How can I know ?

just list the ruleset and see if the rules defined in nftables.conf appears when listing: `nft list ruleset`

> It worked by doesn't persist across reboots.

Sorry, there was a typo, here is the command: `systemctl enable nftables` and reboot.

Anyway, if it still doesn't persist across reboots, ask on the Arch forums. I don't user Arch btw :)
https://wiki.archlinux.org/title/Nftables

**Comment by molitona** [comment] 2021-06-17 13:04
> just list the ruleset and see if the rules defined in nftables.conf appears when listing: nft list ruleset

table inet filter {
	chain input {
		type filter hook input priority filter; policy accept;
		ct state { established, related } accept
		ct state invalid drop
		iifname "lo" accept
		ip protocol icmp accept
		meta l4proto ipv6-icmp accept
		tcp dport 22 accept
		reject
	}

	chain forward {
		type filter hook forward priority filter; policy accept;
		drop
	}

	chain output {
		type filter hook output priority filter; policy accept;
	}
}
table inet mangle {
	chain output {
		type route hook output priority mangle; policy accept;
		icmp type { echo-reply, echo-request } accept
	}
}
table ip opensnitch-filter {
	chain input {
		type filter hook input priority filter; policy accept;
		udp sport 53 queue num 0 bypass
	}
}
table ip6 opensnitch-filter {
	chain input {
		type filter hook input priority filter; policy accept;
		udp sport 53 queue num 0 bypass
	}
}
table ip opensnitch-mangle {
	chain output {
		type route hook output priority mangle; policy accept;
		ct state related,new queue num 0 bypass
	}
}
table ip6 opensnitch-mangle {
	chain output {
		type route hook output priority mangle; policy accept;
		ct state related,new queue num 0 bypass
	}
}

> Sorry, there was a typo, here is the command: systemctl enable nftables and reboot.

I did that.

**Comment by molitona** [comment] 2021-06-22 16:14
Hi , this rule doesn't include zooms.us (only subdomains), what's the problem ?
--> .*\.zoom.us

Also, when I try to open opensnitch from trybar I don' get the window directly (I've to switch to it using ALT+TAB). It occurs only with this software.

**Comment by gustavo-iniguez-goya** [comment] 2021-06-22 23:45
> Hi , this rule doesn't include zooms.us (only subdomains), what's the problem ? --> .*.zoom.us

Try it with: `.*zoom\.us`

> Also, when I try to open opensnitch from trybar I don't get the window directly (I've to switch to it using ALT+TAB). It occurs only with this software.

We're aware of that problem on KDE. Will be fixed soon.

**Comment by gustavo-iniguez-goya** [comment] 2021-07-07 10:33
I'm closing this issue because I think I've all the explanations are already explained :)
If you have more doubts, please, open a new topic on [Discussions](https://github.com/evilsocket/opensnitch/discussions)

**Closed by gustavo-iniguez-goya** 2021-07-07 10:33 UTC
