### ISSUE TITLE
GUI noy load new rules until ui reopen (ver 1.4.0.rc.2.r26)

### ISSUE THREAD

**Issue by Maziar123** [evilsocket/opensnitch#452] opened 2021-07-07 11:37 UTC
Hi

I use in manjaro (updated)

in ver 1.4.0.rc.2.r26  the rules added via dialogs not loaded  until ui reopen

**Comment by gustavo-iniguez-goya** [comment] 2021-07-07 19:29
Hi @Maziar123 ,

Please, provide examples of rules not loaded until the UI is reopened, and steps on how to reproduce it.
Like: 
- Screenshot of the initial pop-up that creates the rule.
- Duration of the rule.
- If the Duration is "always", post the .json located under `/etc/opensnitchd/rules/`

**Comment by Maziar123** [comment] 2021-07-08 06:07
any popup dialog 

any duration in UI  to forever
duration in nodes : one

**Comment by gustavo-iniguez-goya** [comment] 2021-07-09 13:39
Sorry @Maziar123 , I don't understand what this problem is about.

Please, describe the steps to reproduce the issue in great detail, for example:
- Execute command xxxx
- In the pop-up select [x] From this command, Duration: 30s, etc.
- Open the UI, Tab Rules
- The list of rules is empty.
- Close the UI, Open the UI again, et voilà, the rules appear.

**Comment by Maziar123** [comment] 2021-07-10 08:31
exact your comment !


In the pop-up select allow or deny  
Open the UI, Tab Rules
The list of rules is empty.
Close the UI, Open the UI again, et voilà, the rules appear

**Comment by gustavo-iniguez-goya** [comment] 2021-07-13 09:02
aah, ok ok. Yes, in some systems this behaviour can occur. The problem is that the GUI elements are only updated when a new event occur, like when a new connection is established.

Could you verify that when you create a new event the rules list is updated without closing the GUI?

Having firefox allowed:
- execute "ping github.com"
- A new pop-up will appear, click on allow, and verify that the rule is not present in the list.
- Open firefox and go to fsf.org
- See if the rules list has been refreshed (without closing the GUI).

I'll try to reproduce it in my machine.

**Comment by gustavo-iniguez-goya** [comment] 2021-07-17 00:07
@Maziar123 could you close the UI and launch it from a terminal? `$ opensnitch-ui`

See if it outputs any errors please.

**Comment by Maziar123** [comment] 2021-07-18 08:20
yes same happen in arch linux

**Comment by gustavo-iniguez-goya** [comment] 2021-07-18 23:16
Please, close the UI by right-clicking on the systray icon and click on Close, and launch it from a terminal:

`$ opensnitch-ui`

See if it outputs any error messages, and if so post them here.

**Comment by Maziar123** [comment] 2021-07-19 05:38
opensnitch-ui
Loading translations: /usr/lib/python3.9/site-packages/opensnitch/i18n locale: en_US
new node connected, listening for client responses... /tmp/osui.sock

run normally

**Comment by gustavo-iniguez-goya** [comment] 2021-07-22 13:16
@MarkoShiva I just installed 1.4.0.rc.3.r1 on Manjaro, and rules and connections show up on the GUI without having to close and relaunch it.

So I suggest you to remove it completely and reinstall it again. This problem can be related to the other issue #451

**Comment by Maziar123** [comment] 2021-07-22 13:29
have full procedure for sure FULL cleanup ?
and how backup & restore last rules ?

**Comment by gustavo-iniguez-goya** [comment] 2021-07-22 14:00
backup rules: `sudo cp -R /etc/opensntichd/rules/ rules-backup`
restore rules: `sudo cp -R rules-backup/* /etc/opensnitchd/rules/`

uninstall (I don't user arch btw, so maybe there're other ways of doing this):
```
$ yay -R opensnitch-git
$ sudo systemctl stop opensnitchd
$ sudo systemctl disable opensnitchd
$ pkill -15 opensnitch-ui
```

oddly, after uninstalling opensnitch-git the GUI and the daemon keeps running, despite of `/etc/opensnitchd/rules` being deleted.

Be sure that the daemon and the GUI are not running:
`$ pgrep -a opensnitch` <- output should be nothing

`$ sudo rm -rf /etc/opensnitchd/`

install:
```
$ sudo yay -S opensnitch-git
$ sudo systemctl enable opensnitchd
$ sudo systemctl start opensnitchd
$ opensnitch-ui
```

**Comment by Maziar123** [comment] 2021-07-23 08:34
i test as your comment :
with full cleanup and also for sure i don't load old rules :

this problem not solved . more detail : i think when we add some rules it have slow and slower and many time to show new rules 
now over 5~10 sec !

also in Events Tab when i click  delete all  over 10 sec need to delete old rules !

**Comment by gustavo-iniguez-goya** [comment] 2021-07-23 14:07
please, delete all your rules from `/etc/opensnitchd/` (rm -rf /etc/opensnitchd/rules/*), restart the service and confirm if the rules are added to the list without closing the GUI.

**Comment by gustavo-iniguez-goya** [comment] 2021-09-01 11:57
closing due to loack of feedback. In order to continue debugging this issue, provide the information that is requested on this template:
https://github.com/evilsocket/opensnitch/issues/new?assignees=&labels=&template=bug_report.md&title=

**Closed by gustavo-iniguez-goya** 2021-09-01 11:57 UTC
