### ISSUE TITLE
GUI Scaling

### ISSUE THREAD

**Issue by Aiyarree** [evilsocket/opensnitch#182] opened 2018-07-16 21:26 UTC
Please make it correctly scale with higher resolutions.
Even at simple 200% it is unusable - what makes it next to worthless in daily work.

- Tested with Ubuntu Bionic and Budgie Desktop on 4k -

**Comment by MiWCryptAnalytics** [comment] 2018-09-18 04:02
Fixed with #203

**Closed** 2018-10-07 23:54 UTC

**Comment by B4rabbas** [comment] 2018-12-01 20:47
Builded today and I have the issue still there
![screenshot openshot](https://user-images.githubusercontent.com/36156012/49332728-ae2d7a80-f5b2-11e8-80e5-34120f5f6dcf.png)

**Comment by Bezierr** [comment] 2022-12-01 15:38
I can confirm that the issue is still there with the latest version of OpenSnitch: UI does not scale to 200% on Linux Mint Mate 20.2 .

**Comment by gustavo-iniguez-goya** [comment] 2022-12-03 19:05
hey @B4rabbas , the title of that dialog reads "v1.0.0b" is that correct? which version did you build?
