### ISSUE TITLE
Firewall rules remain effective when disabled

### ISSUE THREAD

**Issue by BobSquarePants** [evilsocket/opensnitch#676] opened 2022-06-23 05:50 UTC
When I disable the firewall -->
![firewall_disabled](https://user-images.githubusercontent.com/23012674/175224357-083b473f-4c86-4e09-abd6-d741cd7a1d12.png)

The rule stay in place `nft list ruleset`

I've try a `nft -f /etc/nftables.conf` to reload only mine... but after a couple of second the one from opensnitch re appear...

---

- OpenSnitch version :[v1.6.0-rc.1](https://github.com/evilsocket/opensnitch/releases/tag/v1.6.0-rc.1)
- OS: Devuan
- Window Manager: XFCE
- Kernel version: Linux 5.10.0-9-amd64 .1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux

**Comment by gustavo-iniguez-goya** [comment] 2022-06-23 09:21
When disabling the firewall there should be only rules to intercept network connections.

Please, enable DEBUG logs, reproduce the issue and post the file /var/log/opensnitchd.log.

I'll try to reproduce it also on devuan.

**Comment by BobSquarePants** [comment] 2022-06-23 10:04
Will do.

**Comment by BobSquarePants** [comment] 2022-06-27 05:05
I got the following when I tried to change the log level -->
![debug](https://user-images.githubusercontent.com/23012674/175863795-c85d2d0b-c312-44b1-b107-88690dba10f9.png)

**Comment by gustavo-iniguez-goya** [comment] 2022-06-27 08:29
That's because devuan doesn't automount /sys/kernel/debug, which is needed for eBPF to work. I fixed it a couple of days ago: 
https://github.com/evilsocket/opensnitch/blob/f54eb789ffec4449b48131a076dd65cf95561aad/daemon/procmon/ebpf/utils.go#L11-L16

you can mount it as follow: `mount -t debugfs none /sys/kernel/debug/` and restart opensnitch after that

In order to make it permanent add it to fstab:

`debugfs    /sys/kernel/debug      debugfs  defaults  0 0`

**Comment by gustavo-iniguez-goya** [comment] 2022-07-09 19:55
Closing due to lack of information. reopen when you collect the requested information.

**Closed by gustavo-iniguez-goya** 2022-07-09 19:55 UTC
