### ISSUE TITLE
Slow performance loading some web pages

### ISSUE THREAD

**Issue by Techtonictools** [evilsocket/opensnitch#481] opened 2021-08-25 01:52 UTC
I've been using OpenSnitch starting on a laptop with infrequent use and now I'm using it on my main PC and laptop on a daily basis. It is such a great tool. I've never used or seen anything like it (I don't run mac now) and I'm using it to block Microsoft from trying to update my VM through their back doors and hacks they added so that they can force-feed updates and control my PC. It is also useful to block data mining of my activity on the web and data mining on the PC itself. OpenSnitch additionally enables me to reduce being manipulated through ads on the web and it brings awareness about what apps want to phone home, giving me control of deciding who can phone home and who cannot. 

**Describe the bug**
I have OpenSnitch configured so that everything is blocked except for domains in an exception list. Then I maintain that list of approved sites. The issue I've been hitting is it takes a long time to load some of the heavy websites. Sites that seem to have lots of libraries, requests to complete and code to load like weather underground (WU) does, those sites reproduce a performance issue. Some sites load quickly enough and there isn't any perf issue, like when using old.reddit.com, posting, searching, etc. 

I had previously used a tool called Fiddler on Windows to block all http requests that respected the system proxy, except for websites in a list, and I'd surf the web using it for protection. When I was using that setup and loaded WU, it did not have a slow down. I know that Fiddler is not a full software proxy like OpenSnitch, but I think that when using Fiddler in that way to load WU, it demonstrated that failing requests doesn't make the page take a long time to load.

The wait time I'm experiencing to load WU with OpenSnitch is about 68 seconds before seeing any rendering at all and before load completes. With OpenSnitch off and clearing the browser cache, the page loaded in 4 seconds. Tor (unrestricted in OpenSnitch) loads the page in 7 seconds. Tor-like speed would be great. Could there be performance improvements made for the web surfing scenario in OpenSnitch?

**To Reproduce**
	1. Modify the attached rules to include a correct directory path to store the exception list in
	2. Create the exception list from using the domains listed below and stick it in that path in step 1
	3. Launch Firefox and clear the cache if the WU site has been visited before
	4. Enter WU in the address bar, invoke it and begin timing https://www.wunderground.com/forecast/us/wa/seattle
	5. End timing when you see the page beginning to render

**Expected behavior (optional)**
	1. Some fonts won't load, there will be spinners that never die and the page may look incomplete. 
	2. The page will have what looks like an HTML canvas drawing of the 10 day forecast that is completely legible and usable with a mouse-over.
	3. Less than 15 second load time. I don't know what is reasonable since I don't know what work is being done for filtering the requests. 15 seconds is just an arbitrary number.

**OS (please complete the following information):**
The perf issue reproduces on my Macbook Pro 17", but it also reproduces on a custom PC that is much faster. Both have an unused wired NIC and WiFi. Both use the same internet connection/gateway. The config:

	OpenSnitch 1.4.0rc4
	Debian GNU/Linux 11 (bullseye)
	Gnome 3.38.5
	Firefox 78.13.0esr 
	Tor 10.5.5
	USB NIC: Bus 003 Device 003: ID 148f:761a Ralink Technology, Corp. MT7610U ("Archer T2U" 2.4G+5G WLAN Adapter
	00:19.0 Ethernet controller: Intel Corporation 82579V Gigabit Network Connection (rev 05)
	Intel® Core™ i7-3930K CPU @ 3.20GHz × 12 
	24 GB RAM

**Additional context**
Traceroute

	anon@dev:~$ traceroute wunderground.com
	traceroute to wunderground.com (23.212.36.241), 30 hops max, 60 byte packets
	 1  _gateway (192.168.43.1)  2.769 ms  3.063 ms  4.153 ms
	 2  202.sub-66-174-26.myvzw.com (66.174.26.202)  74.140 ms  67.462 ms  74.276 ms
	 3  * * *
	 4  50.sub-69-83-152.myvzw.com (69.83.152.50)  67.260 ms  73.449 ms  73.770 ms
	 5  * * *
	 6  76.sub-69-83-128.myvzw.com (69.83.128.76)  73.207 ms  76.739 ms  60.019 ms
	 7  135.sub-69-83-129.myvzw.com (69.83.129.135)  71.213 ms  71.544 ms  71.528 ms
	 8  0.csi1.WJRDUT30-MSE01-BB-SU1.ALTER.NET (140.222.7.46)  76.963 ms  77.048 ms  76.751 ms
	 9  * * *
	10  * * *
	11  0.ae2.GW8.LAX15.ALTER.NET (140.222.3.107)  96.008 ms  90.581 ms 0.ae1.GW8.LAX15.ALTER.NET (140.222.3.105)  90.940 ms
	12  152.179.21.130 (152.179.21.130)  91.456 ms  87.283 ms  109.814 ms
	13  * * *
	14  * * *
	15  * * *
	16  * * *
	17  * * *
	18  * * *
	19  * * *
	20  * * *
	21  * * *
	22  * * *
	23  * * *
	24  * * *
	25  * * *
	26  * * *
	27  * * *
	28  * * *
	29  * * *
	30  * * *
	anon@dev:~$ 

Exception list for WU

	127.0.0.1 api3.weather.com
	127.0.0.1 api2.weather.com
	127.0.0.1 api0.weather.com
	127.0.0.1 api1.weather.com
	127.0.0.1 api.weather.com
	127.0.0.1 api.mapbox.com
	127.0.0.1 dsx.weather.com 
	127.0.0.1 www.wunderground.com
	127.0.0.1 wunderground.com

[rules.zip](https://github.com/evilsocket/opensnitch/files/7042970/rules.zip)

**Comment by gustavo-iniguez-goya** [comment] 2021-08-25 11:41
> The wait time I'm experiencing to load WU with OpenSnitch is about 68 seconds before seeing any rendering at all and before load completes. With OpenSnitch off and clearing the browser cache, the page loaded in 4 seconds. Tor (unrestricted in OpenSnitch) loads the page in 7 seconds. Tor-like speed would be great. Could there be performance improvements made for the web surfing scenario in OpenSnitch?

Sure. I think in this case the problem will be the blocklists, I've experienced similar issues on some websites, did you try it out without the blocklists rules?

I'll take a look at it.

**Comment by gustavo-iniguez-goya** [comment] 2021-08-25 16:32
Yes, I've reproduced it, and it's the same problem I already saw. I think the problem is that we're just dropping the requests instead of rejecting them , so in some cases the apps wait until the DNS resolution times out. I didn't find a way of rejecting them with libnetfilter-queue. One way of fixing this issue could be replying a DNS answer poiting to localhost.

**Comment by Techtonictools** [comment] 2021-08-28 18:56
Thanks for laying that out, gustavo. I started to read the code path going backwards from onPacket for this issue and also for issue #482 . All these types, libraries and golang are new to me. I want to read up on all the libraries and learn how this program works so I can understand it.

**Comment by gustavo-iniguez-goya** [comment] 2021-09-06 13:22
I'm starting to feel confident with the Action: reject, it seems to work fine (if it improves web pages loading times is another story). Maybe I'll add it for this release:

deny:
```
$ time curl duckduckgo.com
curl: (6) Could not resolve host: duckduckgo.com

real    0m20,049s
user    0m0,007s
sys     0m0,012s
```

reject:
```
$ time curl duckduckgo.com
curl: (6) Could not resolve host: duckduckgo.com

real    0m0,043s
user    0m0,012s
sys     0m0,006s
```

I don't know if you mentioned it already, but could you reproduce this problem using "proc" monitor method? I want to discard that it's not due to the ebpf module.

**Comment by Techtonictools** [comment] 2021-09-06 17:30
That looks like a substantial improvement. I set the Process monitor
method in the UI to Proc just now and re-ran the scenario. I didn't see
a performance change. WU took longer than a minute time to begin to
load.

**Comment by gustavo-iniguez-goya** [comment] 2022-01-26 16:35
hey! I think this issue is resolved in latest RC2: https://github.com/evilsocket/opensnitch/releases/tag/v1.5.0-rc.2

So I'm closing this now. If the issue remains, please reopen it and we'll take a look.

**Closed by gustavo-iniguez-goya** 2022-01-26 16:35 UTC
