### ISSUE TITLE
1.5.1 daemon error on upgrade from previous version

### ISSUE THREAD

**Issue by themighty1** [evilsocket/opensnitch#679] opened 2022-06-25 12:03 UTC
On Ubuntu 20.04 after I install https://github.com/evilsocket/opensnitch/releases/download/v1.5.1/opensnitch_1.5.1-1_amd64.deb with

> sudo dpkg --install ./opensnitch_1.5.1-1_amd64.deb

and start it with 

> sudo service opensnitch start

I see with sudo service opensnitch status

● opensnitch.service - OpenSnitch is a GNU/Linux application firewall.
     Loaded: loaded (/lib/systemd/system/opensnitch.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2022-06-25 14:52:31 +03; 5min ago
       Docs: https://github.com/gustavo-iniguez-goya/opensnitch/wiki
    Process: 1885801 ExecStartPre=/bin/mkdir -p /etc/opensnitchd/rules (code=exited, status=0/SUCCESS)
   Main PID: 1885802 (opensnitchd)
      Tasks: 16 (limit: 18376)
     Memory: 49.3M
     CGroup: /system.slice/opensnitch.service
             └─1885802 /usr/bin/opensnitchd -rules-path /etc/opensnitchd/rules

Jun 25 14:52:31 pc systemd[1]: Starting OpenSnitch is a GNU/Linux application firewall....
Jun 25 14:52:31 pc systemd[1]: Started OpenSnitch is a GNU/Linux application firewall..
Jun 25 14:52:31 pc opensnitchd[1885802]: [2022-06-25 11:52:31]  IMP  Starting opensnitch-daemon v1.5.1
Jun 25 14:52:31 pc opensnitchd[1885802]: [2022-06-25 11:52:31]  INF  Loading rules from /etc/opensnitchd/rules ...
Jun 25 14:52:31 pc opensnitchd[1885802]: [2022-06-25 11:52:31]  ERR  Error parsing configuration /etc/opensnitchd/default-config.json: unexpected end of JSON input
Jun 25 14:52:31 pc opensnitchd[1885802]: [2022-06-25 11:52:31]  ERR  Error reading firewall configuration from disk /etc/opensnitchd/system-fw.json: open /etc/opensnitchd/system-fw.json: no such file or directory
Jun 25 14:52:31 pc opensnitchd[1885802]: [2022-06-25 11:52:31]  INF  Using iptables firewall
Jun 25 14:52:31 pc opensnitchd[1885802]: [2022-06-25 11:52:31]  INF  Running on netfilter queue #0 ...

There is no logging activity according to:
tail -f /var/log/opensnitchd.log

mkdir ls /etc/opensnitchd shows there is only 1 empty rules folder.

What can I do? why wasnt default-config.json created in the first place?

**Comment by gustavo-iniguez-goya** [comment] 2022-06-25 12:32
hey @themighty1 ! glad to see you around here again :)

As far as I can tell , config files are distributed and installed fine on ubuntu 20.04:
```console
ga@ono-sendai:/tmp/x$ dpkg -x opensnitch_1.5.1-1_amd64.deb xx
ga@ono-sendai:/tmp/x$ ls xx/
etc  lib  usr
ga@ono-sendai:/tmp/x$ ls xx/etc/
init.d  logrotate.d  opensnitchd
ga@ono-sendai:/tmp/x$ ls xx/etc/opensnitchd/
default-config.json  opensnitch.o  system-fw.json
```

```console
ga@ono-sendai:/tmp/x$ dpkg-deb -R opensnitch_1.5.1-1_amd64.deb u
ga@ono-sendai:/tmp/x$ cat u/DEBIAN/conffiles 
/etc/init.d/opensnitch
/etc/logrotate.d/opensnitch
/etc/opensnitchd/default-config.json
/etc/opensnitchd/opensnitch.o
/etc/opensnitchd/system-fw.json
```

```console
ubuntu@ubuntu:~$ sudo dpkg --install ./tmp/x/opensnitch_1.5.1-1_amd64.deb 
Selecting previously unselected package opensnitch.
(Reading database ... 188549 files and directories currently installed.)
Preparing to unpack .../x/opensnitch_1.5.1-1_amd64.deb ...
Unpacking opensnitch (1.5.1-1) ...
Setting up opensnitch (1.5.1-1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/opensnitch.service → /lib/systemd/system/opensnitch.service.
Processing triggers for systemd (245.4-4ubuntu3.15) ...
ubuntu@ubuntu:~$ ls /etc/opensnitchd/
default-config.json  opensnitch.o  rules  system-fw.json
ubuntu@ubuntu:~$ pgrep opensn -a
10851 /usr/bin/opensnitchd -rules-path /etc/opensnitchd/rules
ubuntu@ubuntu:~$
```

**Comment by gustavo-iniguez-goya** [comment] 2022-06-25 12:34
Try installing it with debug:

```console
ubuntu@ubuntu:~$ sudo dpkg --debug=200 --install ./tmp/x/opensnitch_1.5.1-1_amd64.deb
```

did you upgrade it?

**Comment by themighty1** [comment] 2022-06-25 13:09
Hi, @gustavo-iniguez-goya, thanks for the tip. 
Before I opened this isuue, I had uninstalled the previous version with sudo dpkg --remove opensnitch.

I finally resolved the issue. It was one of 2 (or both)  things which I didnt try before, I did

> sudo dpkg --purge opensnitch
> and I manually deleted /etc/init.d/opensnitch

Thanks

**Comment by gustavo-iniguez-goya** [comment] 2022-06-25 14:28
I'm unable to reproduce it. But maybe, just maybe, dpkg doesn't seem to fire postrm script, so uninstalling it with dpkg doesn't stop the process and maybe that caused some problem. With apt seems to stop it:

With dpkg:
```console
ubuntu@ubuntu:~$ sudo dpkg --purge opensnitch
(Reading database ... 189655 files and directories currently installed.)
Removing opensnitch (1.5.1-1) ...
Purging configuration files for opensnitch (1.5.1-1) ...
dpkg: warning: while removing opensnitch, directory '/etc/opensnitchd' not empty so not removed
Processing triggers for systemd (245.4-4ubuntu3.15) ...
ubuntu@ubuntu:~$ ls /etc/opensnitchd/
rules
ubuntu@ubuntu:~$ pgrep opensn
14793
ubuntu@ubuntu:~$
```

With apt:
```console
ubuntu@ubuntu:~$ sudo dpkg --install ./tmp/x/opensnitch_1.5.1-1_amd64.deb 
Unpacking opensnitch (1.5.1-1) ...
Setting up opensnitch (1.5.1-1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/opensnitch.service → /lib/systemd/system/opensnitch.service.
Processing triggers for systemd (245.4-4ubuntu3.15) ...
ubuntu@ubuntu:~$ pgrep opensn
14793
ubuntu@ubuntu:~$ pgrep opensn -a
14793 /usr/bin/opensnitchd -rules-path /etc/opensnitchd/rules
ubuntu@ubuntu:~$ sudo apt remove --purge opensnitch
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  opensnitch*
0 upgraded, 0 newly installed, 1 to remove and 311 not upgraded.
After this operation, 24.8 MB disk space will be freed.
Do you want to continue? [Y/n] 
(Reading database ... 189655 files and directories currently installed.)
Removing opensnitch (1.5.1-1) ...
(Reading database ... 188555 files and directories currently installed.)
Purging configuration files for opensnitch (1.5.1-1) ...
dpkg: warning: while removing opensnitch, directory '/etc/opensnitchd' not empt
y so not removed
Processing triggers for systemd (245.4-4ubuntu3.15) ...
ubuntu@ubuntu:~$ pgrep opensn -a
ubuntu@ubuntu:~$
```

**Comment by gustavo-iniguez-goya** [comment] 2022-09-30 19:33
closing since I didn't reproduce it and no one else has complained on this.

**Closed by gustavo-iniguez-goya** 2022-09-30 19:33 UTC
