### ISSUE TITLE
systemd seccomp filters cause systemd-timesyncd core dumps on Kernel 6.11 when an app uses eBPF modules

### ISSUE THREAD

**Issue by XZVB12** [evilsocket/opensnitch#1205] opened 2024-10-04 20:32 UTC
Include the following information:
 - OpenSnitch version: 1.6.6
 - OS: Manjaro linux
 - Version: 24.1
 - Window Manager: KDE / Kwin
 - Kernel version: 6.11.0 - 6.11.1

**To Reproduce**
Describe in detail as much as you can what happened.

1. build eBPF modules,for example http://aur.archlinux.org/packages/opensnitch-ebpf-module
2. reboot
3. systemctl status systemd-timesyncd

This issue appears on 6.11 kernel and does not affect older version. 
A more detailed discussion: https://github.com/systemd/systemd/issues/34615

Removing eBPF modules solves the problem.

**Comment by gustavo-iniguez-goya** [comment] 2024-10-07 23:14
Hi @XZVB12 ,

I haven't analyzed nor try to reproduce this issue, but per similar cases we've had in the past, this is usually a bug in the other program (systemd-timesyncd in this case). We used to crash Transmission for example, or even the kernel, because there were some conditions not handled correctly (delayed connections, connections unexpectedly blocked/killed, ...)

I'll try to reproduce it, but before that some questions:
 - is this a "regular" kernel or a tuned kernel (liquorix, etc)? 
 - do you have a rule to allow systemd-timesyncd?
 - could you change the LogLevel to DEBUG, and make systemd-timesyncd crash again? then copy /var/log/opensnitchd.log to /tmp , get the full-time of the coredump (ls -l --full-time /var/lib/coredump/...) and try to correlate the date of the core with the opensnitch logs, to see if we can obtain some hints of what was doing the daemon.

On the other hand, @flat commented on https://github.com/systemd/systemd/issues/34615#issuecomment-2394479115: 
> I also notice it was giving me an issue with python running with systemd's SyscallFilters enabled and that is how I figured out what was causing it due to strace showing me uretprobe()                             = -1 ENOSYS (Function not implemented)

Could you post the output of  `~ $ sudo opensnitchd -check-requirements`? in order to see if the uprobes have been removed from the kernel 6.11 configuration.

Thank you!

**Comment by XZVB12** [comment] 2024-10-08 09:09
> * is this a "regular" kernel or a tuned kernel (liquorix, etc)?

Yes, this is "regular" Manjaro Linux kernel
> * do you have a rule to allow systemd-timesyncd?

Yes. 
![изображение](https://github.com/user-attachments/assets/c994253a-35c5-40e2-86ce-c674c91a5468)

> * could you change the LogLevel to DEBUG, and make systemd-timesyncd crash again? then copy /var/log/opensnitchd.log to /tmp , get the full-time of the coredump (ls -l --full-time /var/lib/coredump/...) and try to correlate the date of the core with the opensnitch logs, to see if we can obtain some hints of what was doing the daemon.

I’ll try it later

> Could you post the output of `~ $ sudo opensnitchd -check-requirements`? in order to see if the uprobes have been removed from the kernel 6.11 configuration.

```
Checking system requirements for kernel version 6.11.2-2-MANJARO
------------------------------------------------------------------------------

Checking => CONFIG_KPROBES=y
Checking => CONFIG_KPROBES_ON_FTRACE=y
Checking => CONFIG_HAVE_KPROBES=y
Checking => CONFIG_HAVE_KPROBES_ON_FTRACE=y
Checking => CONFIG_KPROBE_EVENTS=y

* kprobes        ✔

Checking => CONFIG_UPROBES=y
Checking => CONFIG_UPROBE_EVENTS=y

* uprobes        ✔

Checking => CONFIG_FTRACE=y

* ftrace         ✔

Checking => CONFIG_HAVE_SYSCALL_TRACEPOINTS=y
Checking => CONFIG_FTRACE_SYSCALLS=y

* syscalls       ✔

Checking => CONFIG_NETFILTER_NETLINK_QUEUE=[my]
Checking => CONFIG_NFT_QUEUE=[my]
Checking => CONFIG_NETFILTER_XT_TARGET_NFQUEUE=[my]

* nfqueue        ✔

Checking => CONFIG_NETFILTER_NETLINK=[my]
Checking => CONFIG_NETFILTER_NETLINK_QUEUE=[my]
Checking => CONFIG_NETFILTER_NETLINK_ACCT=[my]

* netlink        ✔

Checking => CONFIG_INET_DIAG=[my]
Checking => CONFIG_INET_TCP_DIAG=[my]
Checking => CONFIG_INET_UDP_DIAG=[my]
Checking => CONFIG_INET_DIAG_DESTROY=[my]

* net diagnostics        ✔
```

**Comment by XZVB12** [comment] 2024-10-08 10:34
> * could you change the LogLevel to DEBUG, and make systemd-timesyncd crash again?

According to systemd-coredump event occurred at 13:25:27
```
sudo coredumpctl info 3603
PID: 3603 (systemd-timesyn)
UID: 977 (systemd-timesync)
GID: 977 (systemd-timesync)
Signal: 11 (SEGV)
Timestamp: Tue 2024-10-08 13:25:27
```
For this time in opensnitch log there are the following entries:
```

[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m [eBPF exit event] -> 3587
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m [eBPF exit event inCache] -> 3587
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m [eBPF exit event] -> 3590
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m [eBPF exit event inCache] -> 3590
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m [eBPF exec event] ppid: 1, pid: 3603, /usr/bin/opensnitchd -> [/usr/lib/systemd/systemd-executor --deserialize 50 --log-level info --log-target journal-or-kmsg]
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m [eBPF event inCache] -> 3603
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m new connection udp => 41641:192.168.0.2 -> 1.1.1.1 (0.arch.pool.ntp.org):53 uid: 977, mark: 0
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m [ebpf conn] not in cache, but in execEvents: udp41641192.168.0.21.1.1.153, 3603 -> /usr/lib/systemd/systemd-timesyncd
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m [ebpf conn] adding item to cache: udp41641192.168.0.21.1.1.153
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m [1m[32mâ[0m[0m [1m/usr/lib/systemd/systemd-timesyncd[0m -> 41641:[1m192.168.0.2[0m => [1m0.arch.pool.ntp.org (1.1.1.1)[0m:53, mark: 0 ([32mallow-always-simple-usr-lib-systemd-systemd-timesyncd[0m)
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m new connection udp => 41641:192.168.0.2 -> 1.1.1.1 (0.arch.pool.ntp.org):53 uid: 977, mark: 0
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m error deleting ebpf entry: unable to delete element: no such file or directory
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m [ebpf conn] in cache: udp41641192.168.0.21.1.1.153, 3603 -> /usr/lib/systemd/systemd-timesyncd
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m [1m[32mâ[0m[0m [1m/usr/lib/systemd/systemd-timesyncd[0m -> 41641:[1m192.168.0.2[0m => [1m0.arch.pool.ntp.org (1.1.1.1)[0m:53, mark: 0 ([32mallow-always-simple-usr-lib-systemd-systemd-timesyncd[0m)
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m New DNS record: 89.221.207.113 -> 0.arch.pool.ntp.org
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m New DNS record: 82.142.168.18 -> 0.arch.pool.ntp.org
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m New DNS record: 91.206.16.3 -> 0.arch.pool.ntp.org
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m New DNS record: 162.159.200.123 -> 0.arch.pool.ntp.org
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m [eBPF exec event] ppid: 1, pid: 3606, /usr/bin/opensnitchd -> [/usr/lib/systemd/systemd-executor --deserialize 113 --log-level info --log-target journal-or-kmsg]
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m [eBPF event inCache] -> 3606
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m [eBPF exit event] -> 3603
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m [eBPF exit event inCache] -> 3603
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m [eBPF exit event] -> 3606
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m [eBPF exit event inCache] -> 3606
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m client.disconnect()
[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m UI auth: simple
```
The error I see here: `[2m[2024-10-08 13:25:27][0m [2m[30m[100m DBG [0m error deleting ebpf entry: unable to delete element: no such file or directory`

I attached a log file with information where systemd-timesync starts, so you should easily find . Maybe it will help more
[opensnitchd cut.log](https://github.com/user-attachments/files/17291962/opensnitchd.cut.log)

**Comment by gustavo-iniguez-goya** [comment] 2024-10-08 12:19
thank you @XZVB12 !

I've managed to reproduce it on manjaro with systemd-timesyncd 256.6 and kernel 6.11.0.6-MANJARO.

The problematic ebpf module is opensnitch-dns.o , if you rename it, systemd-timesyncd will stop crashing: 
`~ $ sudo mv /usr/lib/opensnitchd/ebpf/opensnitch-dns.o /usr/lib/opensnitchd/ebpf/opensnitch-dns.o.bak`

I'll try to understand why systemd-timesyncd is crashing and if we can do anything about it.

**Comment by gustavo-iniguez-goya** [comment] 2024-10-08 14:00
we hook 2 libc functions: gethostbyname and getaddrinfo.

systemd-timesyncd crashes when a ebpf hook is attached to uretprobe getaddrinfo (just hooking it, even without reading any variable or register). The hooks for gethostbyname or uprobe getaddrinfo work just fine.

Here's a bpftrace script that causes systemd-timesyncd to crash, without opensnitch running:

[uprobe-getaddrinfo.bt.txt](https://github.com/user-attachments/files/17294279/uprobe-getaddrinfo.bt.txt)

(rename it to .bt, and execute it with `bpftrace uprobe-getaddrinfo.bt`)

so in my opinion, even if we're indirectly causing it, the bug is not in our code. This segfault will occur with any software that hooks libc's  getaddrinfo uretprobe.

**Comment by Flat** [comment] 2024-10-08 14:03
I'd just like to add that I've also had the same issue happen with python using the archlinux reflector script, https://wiki.archlinux.org/title/Reflector so it does not seem to be solely systemd-timesyncd

**Comment by XZVB12** [comment] 2024-10-08 14:27
> so in my opinion, even if we're indirectly causing it, the bug is not in our code. This segfault will occur with any software that hooks libc's getaddrinfo uretprobe.

Any idea what might be the reason? At this point, the kernel is 6.11.2 , and the problem still persists and apparently not noticed.

**Comment by gustavo-iniguez-goya** [comment] 2024-10-08 15:09
no idea @XZVB12 , a change in the 6.11.x kernels maybe.

I've just tested it on kernel 6.10.11-2-MANJARO and systemd-timesyncd doesn't crash, so maybe some of the changes of uretprobes might be the reason of the crashes:

91bd008d4e2b4962ecb9a10e40c2fb666b0aeb92
Merge tag 'probes-v6.11' of git://git.kernel.org/pub/scm/linux/kernel/git/trace/linux-trace

https://lore.kernel.org/lkml/20240719105242.e3c76c4d7958b73ca3428603@kernel.org/T/

      

https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.11

**Comment by Flat** [comment] 2024-10-08 15:29
Sounds like it could be related to this

> - Add uretprobe syscall which speeds up the uretprobe 10-30% faster. This
  syscall is automatically used from user-space trampolines which are
  generated by the uretprobe. If this syscall is used by normal
  user program, it will cause SIGILL. Note that this is currently only
  implemented on x86_64.

**Comment by XZVB12** [comment] 2024-10-08 19:09
> I've just tested it on kernel 6.10.11-2-MANJARO and systemd-timesyncd doesn't crash

I still see this problem in the 6.11.2 kernel. The log I published earlier was made on this Kernel

**Comment by XZVB12** [comment] 2024-10-08 20:27
> Sounds like it could be related to this

So it’s not a bug now, but a new way of "speeds up" ?

**Comment by gustavo-iniguez-goya** [comment] 2024-10-08 21:37
it could be a bug in the 6.11 kernel.

let's summarize what's happening:
 - a user-space app hooks some uretprobes (with this bpftrace script for example https://github.com/user-attachments/files/17294279/uprobe-getaddrinfo.bt.txt).
 - the app and the uretprobes work as expected.
 - restarting `systemd-timesyncd` (256.6, not tested with other versions) crashes with references in the stacktrace to epoll_wait(), sd_event_wait()/_run() and sd_event_loop(). (https://github.com/systemd/systemd/issues/34615#issuecomment-2394085741)
 - the problem can be reproduced with kernel 6.11, but no with 6.10.11 (the only one I've tested).
 - launching `systemd-timesyncd `manually from a root shell doesn't crash.
 - Using `systemctl restart systemd-timesyncd` crashes in loop.

**Comment by gustavo-iniguez-goya** [comment] 2024-10-09 18:45
@XZVB12 , even if this is a kernel bug, the process which is crashing is `systemd-timesyncd`, so there seems to be a condition that they're not controlling, when `systemd-timesyncd` is launched by systemd.

So maybe they should take a look at this problem. They can use the steps above to reproduce it.

**Comment by Flat** [comment] 2024-10-09 19:14
> @XZVB12 , even if this is a kernel bug, the process which is crashing is `systemd-timesyncd`, so there seems to be a condition that they're not controlling, when `systemd-timesyncd` is launched by systemd.
> 
> So maybe they should take a look at this problem. They can use the steps above to reproduce it.
> 

I am pretty sure it is due to the SystemCallFilter option set in the .service file used to launch via systemd. If you remove that line it will not crash. The odd part is it should not be a SIGSEV it should be EPERM or EACCES. Adding uretprobe syscall to the filters does not help either.

**Comment by zquestz** [comment] 2024-10-09 21:20
Just a heads up, this is crashing `stubby` on Arch as well.

**Comment by zquestz** [comment] 2024-10-09 21:28
Just did a test, and removing the SystemCallFilter fixes both the issues on my machine. Oddly enough, you can also get them running again by reinstalling the glibc package... For some reason the SystemCallFilter doesn't trip if you reinstall glibc then run the systemd services...

**Comment by XZVB12** [comment] 2024-10-10 09:15
> Just a heads up, this is crashing `stubby` on Arch as well.

It seems that any distribution with the 6.11 kernel will be affected by this problem

> So maybe they should take a look at this problem. They can use the steps above to reproduce it.

I reopened the discussion and gave links to new information . Perhaps you could also join the discussion, maybe it would be easier to communicate directly.

**Comment by gustavo-iniguez-goya** [comment] 2024-10-11 10:55
Thank you @XZVB12 and @Flat for handling and analyzing this issue.

Hopefully it'll be resolved in the next systemd release.

**Closed by gustavo-iniguez-goya** 2024-10-11 10:55 UTC

**Comment by UnconnectedBedna** [comment] 2024-11-15 21:27
This is back again, but this time the boot freezes for 60s when trying to sync, and then `systemd-timesyncd` fails with core dump.

Same thing happens on 6.6 LTS, (freezes for one minute) BUT the service does NOT fail, only gets stuck for 60s.

If you want me to make a new post I can do that, but since this seems to be some kind of regression, I started by posting here.

**Comment by Flat** [comment] 2024-11-15 22:23
The original issue still hasn't been resolved. libseccomp will need a new release with the syscalls added. https://github.com/seccomp/libseccomp/pull/439 once this has been merged and libseccomp updated it should resolve this issue.

**Comment by UnconnectedBedna** [comment] 2024-11-15 22:30
Ah, that is what is happening.
Strange that it started working on my system, and then regressed again.

I DID try to check seccomp first before posting here with the links referenced (https://github.com/seccomp/libseccomp/issues/438 > https://github.com/seccomp/libseccomp/pull/435) and they looked merged, but clearly there is more judging by the link you provided.

Thank you for the clarification!

**Comment by primalmotion** [comment] 2024-12-31 20:09
It seems the patch from libsecomp has been released (and I run it: 2.5.5) but the issue is still happening.

**Comment by Flat** [comment] 2024-12-31 20:26
2.5.5 is from December 2023, a new version with the patch has not been released yet.

**Comment by primalmotion** [comment] 2025-01-01 17:31
dang it. I misread the date :)

**Comment by XZVB12** [comment] 2025-01-25 01:04
[libseccomp v2.6.0](https://github.com/seccomp/libseccomp/releases/tag/v2.6.0) and [libseccomp v2.5.6](https://github.com/seccomp/libseccomp/releases/tag/v2.5.6)
Finally released, someone tested ?
they are not yet in the repository, when there is time, try to compile from git

**Comment by JurgenCruz** [comment] 2025-02-17 15:56
Is there a way to mark the request as +1 in arch repos to get more attention?

**Comment by XZVB12** [comment] 2025-02-17 16:49
> Is there a way to mark the request as +1 in arch repos to get more attention?

you can try https://bbs.archlinux.org/viewforum.php?id=18 or https://bbs.archlinux.org/viewforum.php?id=44

I have quarreled with these people and don’t want to waste any more time talking to them.

**Comment by UnconnectedBedna** [comment] 2025-02-18 06:22
There is no need to quarrel with anyone, on arch, it is in testing repos and anybody can go ahead and activate the testing repo and try.
https://archlinux.org/packages/core-testing/x86_64/libseccomp/

If you don't want to, then have patience until OTHERS have tested it FOR YOU.
If no bugs are found and the package works, it will be moved to stable after a while.
There is no reason for toxic behavior.

**Comment by XZVB12** [comment] 2025-02-18 13:04
> There is no need to quarrel with anyone, on arch

The cause of the argument was not in the package version/ test repository. I love their distribution, but sometimes the forum communication becomes unbearable. I have been using test repositories for many years and try to help with bug reports, but when your topic is removed instead of understanding what you want to explain I have no desire to do anything.
and yes I already gave a link to this package.

**Comment by atpage** [comment] 2025-03-18 22:08
Ahhh this is the reason NTP wasn't syncing for me in Debian 12.  I suppose it will be a long time before those packages are updated.
