### ISSUE TITLE
Opensnitch gets bypassed on first request

### ISSUE THREAD

**Issue by bugsymaxi** [evilsocket/opensnitch#489] opened 2021-09-03 07:16 UTC
Hi all,

while switching to Debian 11 and installing rc4, i have recently noticed that opensnitch gets bypassed on the first ever request of a bin (when no rules have been created yet for such bin).
Although there is some kind of waiting/idle time, the bin gets executed at some point before the opensnitch dialog is done counting.
However, after the dialog closes and standard rules have been applied (deny until reboot) all further bin requests get denied - as it is supposed to be.

I have also noticed this behavior on boot as some bins were able to initiate connections. Opensnitch has shown the bin dialogs later as packets were already flowing. Consequently, already running bins are not stopped from sending packets - only new instances.

opensnitchd --version: 1.4.0rc4
Operating System: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.10.0-8-amd64
Architecture: x86-64

![bypass1](https://user-images.githubusercontent.com/90026839/131965145-4c627b05-202a-4d1a-85f4-974f9b2f34fb.png)

![bypass2](https://user-images.githubusercontent.com/90026839/131965158-526e5eee-92d4-4aa4-bb94-863d8a9634ba.png)

**Comment by gustavo-iniguez-goya** [comment] 2021-09-03 09:33
Hi @bugsymaxi , welcome!

I can think of 2 reasons why this happened:
1. opensnitchd is crashing when performing the request, so the connection is allowed.
2. The DefaultAction is "allow" and for some reason it's being applied (it shouldn't if the GUI is connected).

So the connections being allowed on boot I'd say that is expected. If you want to deny everything while the GUI is not connected, set the DefaultAction to *deny* in /etc/opensnitchd/default_configuration.json , or using the GUI, in Preferences -> Nodes

Could you execute `journalctl -ar|grep opensnitchd` and see if there're segfaults of `opensnitchd`?

What process monitor method are you using (Preferences -> Nodes)? There's an issue right now with `ebpf`, but the behaviour is the opposite: at some point everything is denied.

**Comment by bugsymaxi** [comment] 2021-09-03 10:43
Thank you for the quick reply. Yes, i am using ebpf.

I was not able to locate a segfault, however the debug revealed the following message while the dialog is on screen:

**`UI is not running or busy, connected: true, running: true`**

Further, it seems opensnitchd is not in sync with my system time.

![image](https://user-images.githubusercontent.com/90026839/131992910-101594e3-db2c-427b-aa69-8fb88df3f4a4.png)

➜  ~ cat /etc/opensnitchd/default-config.json 
```
{
    "Server": {
        "Address": "unix:///tmp/osui.sock",
        "LogFile": "/var/log/opensnitchd.log"
    },
    "DefaultAction": "allow",
    "DefaultDuration": "once",
    "InterceptUnknown": false,
    "ProcMonitorMethod": "ebpf",
    "LogLevel": 0,
    "Firewall": "iptables",
    "Stats": {
        "MaxEvents": 150,
        "MaxStats": 25
    }
} 
```

**Comment by gustavo-iniguez-goya** [comment] 2021-09-03 14:00
> UI is not running or busy, connected: true, running: true

This is normal if there's a pop-up asking (`running: true`) to allow/deny a connection. In this case the DefaultAction is applied.

After analyazing the code I think that this is the expected behaviour. Change the daemon's DefaultAction to deny and see if you reproduce it.

In any case I can't reproduce this behaviour on my debian 11. While the GUI is connected we should apply the GUI's action, rather than the daemon's. I'll take a look at this.

**Comment by gustavo-iniguez-goya** [comment] 2021-09-03 21:08
With latest commit this issue should be fixed. Now the user has full-control over the verdict to apply on connections when:

1) the GUI is not connected (/etc/opensnitchd/default-config.json -> DefaultAction),
2) the GUI is connected and a pop-up is asking to allow/deny a connection (GUI -> Default action),
4) we can't parse a connection or can't get the PID.

For the time being set daemon's DefaultAction to deny. If you can compile the daemon give it a try and let me know if it's fixed.

There's still one piece left: configure daemon's DefaultAction when the user changes UI's DefaultAction.

Thank you for reporting this!

**Closed by gustavo-iniguez-goya** 2021-09-03 21:08 UTC

**Comment by bugsymaxi** [comment] 2021-09-04 19:54
Thank you. I just tested it and it works as expected.
